# MeSH Headings with Semantic Type T047 (Disease or Syndrome)
# Generated on: 2025-06-29T08:51:02.563
# Total headings: 3197

const MESH_T047_HEADINGS = Set{String}([
    "22q11 Deletion Syndrome",
    "46, XX Disorders of Sex Development",
    "46, XX Testicular Disorders of Sex Development",
    "ACTH Syndrome, Ectopic",
    "AIDS Arteritis, Central Nervous System",
    "AIDS Dementia Complex",
    "AIDS-Associated Nephropathy",
    "AIDS-Related Complex",
    "AIDS-Related Opportunistic Infections",
    "Abdominal Abscess",
    "Abducens Nerve Diseases",
    "Abetalipoproteinemia",
    "Abortion, Habitual",
    "Abortion, Incomplete",
    "Abortion, Missed",
    "Abortion, Septic",
    "Abortion, Spontaneous",
    "Abortion, Threatened",
    "Abortion, Veterinary",
    "Abruptio Placentae",
    "Acalculous Cholecystitis",
    "Acanthamoeba Keratitis",
    "Acanthocheilonemiasis",
    "Acanthosis Nigricans",
    "Acatalasia",
    "Accelerated Idioventricular Rhythm",
    "Accessory Nerve Diseases",
    "Acidosis",
    "Acidosis, Lactic",
    "Acidosis, Renal Tubular",
    "Acidosis, Respiratory",
    "Acinetobacter Infections",
    "Acne Conglobata",
    "Acne Keloid",
    "Acne Vulgaris",
    "Acneiform Eruptions",
    "Acquired Hyperostosis Syndrome",
    "Acquired Immunodeficiency Syndrome",
    "Acro-Osteolysis",
    "Acrocallosal Syndrome",
    "Acrodermatitis",
    "Acromegaly",
    "Actinobacillosis",
    "Actinobacillus Infections",
    "Actinomycetales Infections",
    "Actinomycosis",
    "Actinomycosis, Cervicofacial",
    "Acute Aortic Syndrome",
    "Acute Chest Syndrome",
    "Acute Coronary Syndrome",
    "Acute Disease",
    "Acute Febrile Encephalopathy",
    "Acute Generalized Exanthematous Pustulosis",
    "Acute Kidney Injury",
    "Acute Lung Injury",
    "Acute Radiation Syndrome",
    "Acute Retroviral Syndrome",
    "Acute-On-Chronic Liver Failure",
    "Adams-Stokes Syndrome",
    "Addison Disease",
    "Adenomyosis",
    "Adenophorea Infections",
    "Adenoviridae Infections",
    "Adenovirus Infections, Human",
    "Adie Syndrome",
    "Adiposis Dolorosa",
    "Adnexal Diseases",
    "Adrenal Cortex Diseases",
    "Adrenal Gland Diseases",
    "Adrenal Hyperplasia, Congenital",
    "Adrenal Insufficiency",
    "Adrenocortical Hyperfunction",
    "Adrenogenital Syndrome",
    "Adrenoleukodystrophy",
    "Afferent Loop Syndrome",
    "Afibrinogenemia",
    "African Horse Sickness",
    "African Swine Fever",
    "Agammaglobulinemia",
    "Aggressive Periodontitis",
    "Agranulocytosis",
    "Agricultural Workers' Diseases",
    "Aicardi Syndrome",
    "Ainhum",
    "Airway Obstruction",
    "Akathisia, Drug-Induced",
    "Alagille Syndrome",
    "Albuminuria",
    "Alcohol Withdrawal Delirium",
    "Alcohol Withdrawal Seizures",
    "Alcohol-Induced Disorders, Nervous System",
    "Alcohol-Related Disorders",
    "Alcoholic Korsakoff Syndrome",
    "Alcoholic Neuropathy",
    "Aleutian Mink Disease",
    "Alexander Disease",
    "Alice in Wonderland Syndrome",
    "Aliivibrio Infections",
    "Alkalosis",
    "Alkaptonuria",
    "Allergic Fungal Sinusitis",
    "Alopecia",
    "Alopecia Areata",
    "Alphavirus Infections",
    "Alstrom Syndrome",
    "Alternariosis",
    "Altitude Sickness",
    "Alveolar Bone Loss",
    "Alveolitis, Extrinsic Allergic",
    "Alzheimer Disease",
    "Amblyopia",
    "Amebiasis",
    "Amelogenesis Imperfecta",
    "Amenorrhea",
    "Amino Acid Metabolism, Inborn Errors",
    "Amino Acid Transport Disorders, Inborn",
    "Amniotic Band Syndrome",
    "Amyloid Neuropathies",
    "Amyloid Neuropathies, Familial",
    "Amyloidosis",
    "Amyloidosis, Familial",
    "Amyotrophic Lateral Sclerosis",
    "Anaphylaxis",
    "Anaplasmataceae Infections",
    "Anaplasmosis",
    "Ancylostomiasis",
    "Andersen Syndrome",
    "Androgen-Insensitivity Syndrome",
    "Anemia",
    "Anemia, Aplastic",
    "Anemia, Diamond-Blackfan",
    "Anemia, Dyserythropoietic, Congenital",
    "Anemia, Hemolytic",
    "Anemia, Hemolytic, Autoimmune",
    "Anemia, Hemolytic, Congenital",
    "Anemia, Hemolytic, Congenital Nonspherocytic",
    "Anemia, Hypochromic",
    "Anemia, Hypoplastic, Congenital",
    "Anemia, Iron-Deficiency",
    "Anemia, Macrocytic",
    "Anemia, Megaloblastic",
    "Anemia, Myelophthisic",
    "Anemia, Neonatal",
    "Anemia, Pernicious",
    "Anemia, Refractory",
    "Anemia, Refractory, with Excess of Blasts",
    "Anemia, Sickle Cell",
    "Anemia, Sideroblastic",
    "Anetoderma",
    "Aneurysm",
    "Aneurysm, Aortic Arch",
    "Aneurysm, False",
    "Aneurysm, Infected",
    "Aneurysm, Ruptured",
    "Angelman Syndrome",
    "Angina Pectoris",
    "Angina Pectoris, Variant",
    "Angina, Stable",
    "Angiodysplasia",
    "Angioedemas, Hereditary",
    "Angioid Streaks",
    "Angiolymphoid Hyperplasia with Eosinophilia",
    "Angiomatosis",
    "Angiomatosis, Bacillary",
    "Animal Diseases",
    "Anisakiasis",
    "Anisometropia",
    "Ankyloglossia",
    "Ankylosis",
    "Anovulation",
    "Anterior Compartment Syndrome",
    "Anterior Spinal Artery Syndrome",
    "Anterior Wall Myocardial Infarction",
    "Anthracosilicosis",
    "Anthracosis",
    "Anthrax",
    "Anti-Glomerular Basement Membrane Disease",
    "Anti-N-Methyl-D-Aspartate Receptor Encephalitis",
    "Anti-Neutrophil Cytoplasmic Antibody-Associated Vasculitis",
    "Antiphospholipid Syndrome",
    "Antithrombin III Deficiency",
    "Antley-Bixler Syndrome Phenotype",
    "Anuria",
    "Anus Diseases",
    "Anus, Imperforate",
    "Aortic Aneurysm, Thoracic",
    "Aortic Arch Syndromes",
    "Aortic Diseases",
    "Aortic Root Aneurysm",
    "Aortic Stenosis, Subvalvular",
    "Aortic Stenosis, Supravalvular",
    "Aortic Valve Disease",
    "Aortic Valve Insufficiency",
    "Aortic Valve Prolapse",
    "Aortic Valve Stenosis",
    "Aortitis",
    "Ape Diseases",
    "Appendicitis",
    "Arachnoiditis",
    "Arbovirus Infections",
    "Arenaviridae Infections",
    "Argininosuccinic Aciduria",
    "Arrhythmogenic Right Ventricular Dysplasia",
    "Arterial Occlusive Diseases",
    "Arteriosclerosis Obliterans",
    "Arteritis",
    "Arterivirus Infections",
    "Arthritis",
    "Arthritis, Gouty",
    "Arthritis, Infectious",
    "Arthritis, Juvenile",
    "Arthritis, Psoriatic",
    "Arthritis, Reactive",
    "Arthritis, Rheumatoid",
    "Arthropathy, Neurogenic",
    "Arthus Reaction",
    "Asbestosis",
    "Ascariasis",
    "Ascaridiasis",
    "Ascaridida Infections",
    "Ascorbic Acid Deficiency",
    "Aspartylglucosaminuria",
    "Asperger Syndrome",
    "Aspergillosis",
    "Aspergillosis, Allergic Bronchopulmonary",
    "Aspermia",
    "Asphyxia Neonatorum",
    "Asthenia",
    "Asthenopia",
    "Asthenozoospermia",
    "Asthma",
    "Asthma, Exercise-Induced",
    "Asthma, Occupational",
    "Asthma-Chronic Obstructive Pulmonary Disease Overlap Syndrome",
    "Astigmatism",
    "Astroviridae Infections",
    "Asymptomatic Diseases",
    "Asymptomatic Infections",
    "Ataxia Telangiectasia",
    "Atrial Premature Complexes",
    "Atrioventricular Block",
    "Atrophic Maxilla",
    "Atrophic Vaginitis",
    "Atypical Hemolytic Uremic Syndrome",
    "Auditory Diseases, Central",
    "Autoimmune Diseases",
    "Autoimmune Diseases of the Nervous System",
    "Autoimmune Hypophysitis",
    "Autoimmune Lymphoproliferative Syndrome",
    "Autoimmune Pancreatitis",
    "Autonomic Dysreflexia",
    "Autonomic Nervous System Diseases",
    "Autosomal Emery-Dreifuss Muscular Dystrophy",
    "Avitaminosis",
    "Avulavirus Infections",
    "Axial Spondyloarthritis",
    "Azoospermia",
    "Babesiosis",
    "Bacillaceae Infections",
    "Bacteremia",
    "Bacterial Infections",
    "Bacterial Infections and Mycoses",
    "Bacterial Zoonoses",
    "Bacteriuria",
    "Bacteroidaceae Infections",
    "Bacteroides Infections",
    "Balanitis",
    "Balanitis Xerotica Obliterans",
    "Balantidiasis",
    "Balkan Nephropathy",
    "Bardet-Biedl Syndrome",
    "Barrett Esophagus",
    "Barth Syndrome",
    "Bartonella Infections",
    "Bartonellaceae Infections",
    "Bartter Syndrome",
    "Basal Ganglia Cerebrovascular Disease",
    "Basal Ganglia Diseases",
    "Battered Child Syndrome",
    "Beckwith-Wiedemann Syndrome",
    "Behcet Syndrome",
    "Bell Palsy",
    "Benign Paroxysmal Positional Vertigo",
    "Beriberi",
    "Bernard-Soulier Syndrome",
    "Berylliosis",
    "Bicornuate Uterus",
    "Bicuspid Aortic Valve Disease",
    "Bifidobacteriales Infections",
    "Bile Duct Diseases",
    "Bile Reflux",
    "Biliary Atresia",
    "Biliary Dyskinesia",
    "Biliary Tract Diseases",
    "Biotinidase Deficiency",
    "Bird Diseases",
    "Bird Fancier's Lung",
    "Birdshot Chorioretinopathy",
    "Birnaviridae Infections",
    "Birt-Hogg-Dube Syndrome",
    "Blackwater Fever",
    "Blast Crisis",
    "Blastocystis Infections",
    "Blastomycosis",
    "Blepharitis",
    "Blepharoptosis",
    "Blepharospasm",
    "Blind Loop Syndrome",
    "Blindness",
    "Blindness, Cortical",
    "Blood Coagulation Disorders",
    "Blood Coagulation Disorders, Inherited",
    "Blood Group Incompatibility",
    "Blood Platelet Disorders",
    "Blood Protein Disorders",
    "Blood-Borne Infections",
    "Bloom Syndrome",
    "Blue Toe Syndrome",
    "Bluetongue",
    "Bone Cysts",
    "Bone Cysts, Aneurysmal",
    "Bone Demineralization, Pathologic",
    "Bone Diseases",
    "Bone Diseases, Developmental",
    "Bone Diseases, Endocrine",
    "Bone Diseases, Infectious",
    "Bone Diseases, Metabolic",
    "Bone Marrow Diseases",
    "Bone Marrow Failure Disorders",
    "Border Disease",
    "Bordetella Infections",
    "Borna Disease",
    "Borrelia Infections",
    "Botulism",
    "Boutonneuse Fever",
    "Bovine Respiratory Disease Complex",
    "Bovine Virus Diarrhea-Mucosal Disease",
    "Brachial Plexus Neuritis",
    "Brachial Plexus Neuropathies",
    "Brain Abscess",
    "Brain Damage, Chronic",
    "Brain Diseases",
    "Brain Diseases, Metabolic",
    "Brain Diseases, Metabolic, Inborn",
    "Brain Infarction",
    "Brain Ischemia",
    "Brain Stem Infarctions",
    "Branchio-Oto-Renal Syndrome",
    "Breakthrough Infections",
    "Breast Diseases",
    "Breech Presentation",
    "Bronchial Diseases",
    "Bronchial Hyperreactivity",
    "Bronchial Spasm",
    "Bronchiectasis",
    "Bronchiolitis",
    "Bronchiolitis Obliterans",
    "Bronchiolitis Obliterans Syndrome",
    "Bronchiolitis, Viral",
    "Bronchitis",
    "Bronchitis, Chronic",
    "Bronchomalacia",
    "Bronchopneumonia",
    "Bronchopulmonary Dysplasia",
    "Brown-Sequard Syndrome",
    "Brucellosis",
    "Brucellosis, Bovine",
    "Brugada Syndrome",
    "Bruxism",
    "Budd-Chiari Syndrome",
    "Bulbar Palsy, Progressive",
    "Bulbo-Spinal Atrophy, X-Linked",
    "Bunyaviridae Infections",
    "Burkholderia Infections",
    "Burning Mouth Syndrome",
    "Bursitis",
    "Buruli Ulcer",
    "Byssinosis",
    "CADASIL",
    "CHARGE Syndrome",
    "COVID-19",
    "CREST Syndrome",
    "Cafe-au-Lait Spots",
    "Calcinosis",
    "Calciphylaxis",
    "Calcium Metabolism Disorders",
    "Caliciviridae Infections",
    "Callosities",
    "Campomelic Dysplasia",
    "Campylobacter Infections",
    "Canaliculitis",
    "Canavan Disease",
    "Candidemia",
    "Candidiasis",
    "Candidiasis, Chronic Mucocutaneous",
    "Candidiasis, Cutaneous",
    "Candidiasis, Invasive",
    "Candidiasis, Oral",
    "Candidiasis, Vulvovaginal",
    "Capillary Leak Syndrome",
    "Caplan Syndrome",
    "Capsule Opacification",
    "Carbamoyl-Phosphate Synthase I Deficiency Disease",
    "Carbohydrate Metabolism, Inborn Errors",
    "Carcinoid Heart Disease",
    "Cardiac Complexes, Premature",
    "Cardiac Conduction System Disease",
    "Cardiac Tamponade",
    "Cardio-Renal Syndrome",
    "Cardiomyopathies",
    "Cardiomyopathy, Alcoholic",
    "Cardiomyopathy, Dilated",
    "Cardiomyopathy, Hypertrophic",
    "Cardiomyopathy, Hypertrophic, Familial",
    "Cardiomyopathy, Restrictive",
    "Cardiovascular Diseases",
    "Cardiovascular Infections",
    "Cardiovirus Infections",
    "Carney Complex",
    "Caroli Disease",
    "Carotid Artery Diseases",
    "Carotid Artery Thrombosis",
    "Carotid Artery, Internal, Dissection",
    "Carotid Stenosis",
    "Carotid-Cavernous Sinus Fistula",
    "Carpal Tunnel Syndrome",
    "Cartilage Diseases",
    "Castleman Disease",
    "Cat Diseases",
    "Cat-Scratch Disease",
    "Cataplexy",
    "Cataract",
    "Catastrophic Illness",
    "Cattle Diseases",
    "Cauda Equina Syndrome",
    "Causalgia",
    "Cavernous Sinus Syndromes",
    "Cavernous Sinus Thrombosis",
    "Cecal Diseases",
    "Celiac Disease",
    "Central Nervous System Bacterial Infections",
    "Central Nervous System Diseases",
    "Central Nervous System Fungal Infections",
    "Central Nervous System Helminthiasis",
    "Central Nervous System Infections",
    "Central Nervous System Parasitic Infections",
    "Central Nervous System Protozoal Infections",
    "Central Nervous System Viral Diseases",
    "Central Serous Chorioretinopathy",
    "Cephalopelvic Disproportion",
    "Cerebellar Cognitive Affective Syndrome",
    "Cerebellar Diseases",
    "Cerebral Amyloid Angiopathy",
    "Cerebral Amyloid Angiopathy, Familial",
    "Cerebral Arterial Diseases",
    "Cerebral Infarction",
    "Cerebral Intraventricular Hemorrhage",
    "Cerebral Palsy",
    "Cerebral Phaeohyphomycosis",
    "Cerebral Small Vessel Diseases",
    "Cerebral Ventriculitis",
    "Cerebrospinal Fluid Leak",
    "Cerebrospinal Fluid Otorrhea",
    "Cerebrospinal Fluid Rhinorrhea",
    "Cervical Rib Syndrome",
    "Cestode Infections",
    "Chagas Cardiomyopathy",
    "Chagas Disease",
    "Chalazion",
    "Chancroid",
    "Channelopathies",
    "Charcot-Marie-Tooth Disease",
    "Charles Bonnet Syndrome",
    "Chediak-Higashi Syndrome",
    "Cheilitis",
    "Chemical and Drug Induced Liver Injury",
    "Chemical and Drug Induced Liver Injury, Chronic",
    "Chemically-Induced Disorders",
    "Chemotherapy-Induced Febrile Neutropenia",
    "Cherubism",
    "Chiari-Frommel Syndrome",
    "Chickenpox",
    "Chikungunya Fever",
    "Chilaiditi Syndrome",
    "Child Nutrition Disorders",
    "Chlamydia Infections",
    "Chlamydiaceae Infections",
    "Chlamydial Pneumonia",
    "Chlamydophila Infections",
    "Chloracne",
    "Cholangitis",
    "Cholangitis, Sclerosing",
    "Cholecystitis",
    "Cholecystitis, Acute",
    "Cholecystolithiasis",
    "Choledochal Cyst",
    "Choledocholithiasis",
    "Cholelithiasis",
    "Cholera",
    "Cholera Morbus",
    "Cholestasis",
    "Cholestasis, Extrahepatic",
    "Cholestasis, Intrahepatic",
    "Cholesteatoma",
    "Cholesteatoma, Middle Ear",
    "Cholesterol Ester Storage Disease",
    "Choline Deficiency",
    "Chondrocalcinosis",
    "Chondrodysplasia Punctata",
    "Chondrodysplasia Punctata, Rhizomelic",
    "Chondromalacia Patellae",
    "Chondromatosis, Synovial",
    "Chorea Gravidarum",
    "Chorioamnionitis",
    "Chorioretinitis",
    "Choroid Diseases",
    "Choroideremia",
    "Choroiditis",
    "Chromoblastomycosis",
    "Chromosome Disorders",
    "Chronic Disease",
    "Chronic Exertional Compartment Syndrome",
    "Chronic Inducible Urticaria",
    "Chronic Kidney Disease-Mineral and Bone Disorder",
    "Chronic Kidney Diseases of Uncertain Etiology",
    "Chronic Limb-Threatening Ischemia",
    "Chronic Periodontitis",
    "Chronic Traumatic Encephalopathy",
    "Chronic Urticaria",
    "Chronobiology Disorders",
    "Churg-Strauss Syndrome",
    "Chylothorax",
    "Chylous Ascites",
    "Ciliary Motility Disorders",
    "Ciliopathies",
    "Ciliophora Infections",
    "Circoviridae Infections",
    "Citrullinemia",
    "Classical Lissencephalies and Subcortical Band Heterotopias",
    "Classical Swine Fever",
    "Cleft Palate",
    "Cleidocranial Dysplasia",
    "Clonorchiasis",
    "Clostridium Infections",
    "Cluster Headache",
    "Coagulation Protein Disorders",
    "Cobblestone Lissencephaly",
    "Coccidioidal Meningitis",
    "Coccidioidomycosis",
    "Coccidiosis",
    "Cochlear Diseases",
    "Cockayne Syndrome",
    "Coffin-Lowry Syndrome",
    "Cogan Syndrome",
    "Coinfection",
    "Cold Urticaria",
    "Colitis",
    "Colitis, Collagenous",
    "Colitis, Ischemic",
    "Colitis, Lymphocytic",
    "Colitis, Microscopic",
    "Colitis, Ulcerative",
    "Collagen Diseases",
    "Collagenous Sprue",
    "Colonic Diseases",
    "Colonic Diseases, Functional",
    "Colonic Pseudo-Obstruction",
    "Color Vision Defects",
    "Colorado Tick Fever",
    "Coma",
    "Coma, Post-Head Injury",
    "Common Bile Duct Diseases",
    "Common Cold",
    "Common Variable Immunodeficiency",
    "Communicable Diseases",
    "Communicable Diseases, Emerging",
    "Communicable Diseases, Imported",
    "Community-Acquired Infections",
    "Community-Acquired Pneumonia",
    "Compartment Syndromes",
    "Complex Regional Pain Syndromes",
    "Condylomata Acuminata",
    "Cone Dystrophy",
    "Cone-Rod Dystrophies",
    "Congenital Bone Marrow Failure Syndromes",
    "Congenital Cranial Dysinnervation Disorders",
    "Congenital Disorders of Glycosylation",
    "Congenital Hyperinsulinism",
    "Congenital Hypothyroidism",
    "Congenital Microtia",
    "Congenital, Hereditary, and Neonatal Diseases and Abnormalities",
    "Conjunctival Diseases",
    "Conjunctivitis",
    "Conjunctivitis, Acute Hemorrhagic",
    "Conjunctivitis, Allergic",
    "Conjunctivitis, Bacterial",
    "Conjunctivitis, Inclusion",
    "Conjunctivitis, Viral",
    "Connective Tissue Diseases",
    "Coproporphyria, Hereditary",
    "Corneal Diseases",
    "Corneal Dystrophies, Hereditary",
    "Corneal Dystrophy, Juvenile Epithelial of Meesmann",
    "Corneal Perforation",
    "Corneal Ulcer",
    "Corneal Wavefront Aberration",
    "Coronary Aneurysm",
    "Coronary Artery Disease",
    "Coronary Disease",
    "Coronary Occlusion",
    "Coronary Restenosis",
    "Coronary Stenosis",
    "Coronary Thrombosis",
    "Coronary Vasospasm",
    "Coronary-Subclavian Steal Syndrome",
    "Coronaviridae Infections",
    "Coronavirus Infections",
    "Corticobasal Degeneration",
    "Corynebacterium Infections",
    "Costello Syndrome",
    "Cough-Variant Asthma",
    "Cowpox",
    "Coxa Valga",
    "Coxa Vara",
    "Coxsackievirus Infections",
    "Cranial Nerve Diseases",
    "Craniofacial Dysostosis",
    "Craniofacial Fibrous Dysplasia",
    "Craniomandibular Disorders",
    "Craniosynostoses",
    "Creutzfeldt-Jakob Syndrome",
    "Cri-du-Chat Syndrome",
    "Crigler-Najjar Syndrome",
    "Critical Illness",
    "Crohn Disease",
    "Cronkhite-Canada Syndrome",
    "Cross Infection",
    "Croup",
    "Crush Syndrome",
    "Cryoglobulinemia",
    "Cryopyrin-Associated Periodic Syndromes",
    "Cryptococcosis",
    "Cryptogenic Organizing Pneumonia",
    "Cryptosporidiosis",
    "Crystal Arthropathies",
    "Cubital Tunnel Syndrome",
    "Cumulative Trauma Disorders",
    "Cushing Syndrome",
    "Cutis Laxa",
    "Cyclosporiasis",
    "Cystic Fibrosis",
    "Cysticercosis",
    "Cystinosis",
    "Cystinuria",
    "Cystitis",
    "Cystitis, Hemorrhagic",
    "Cystitis, Interstitial",
    "Cystocele",
    "Cytochrome-c Oxidase Deficiency",
    "Cytokine Release Syndrome",
    "Cytomegalovirus Infections",
    "Cytomegalovirus Retinitis",
    "Cytophagaceae Infections",
    "DNA Repair-Deficiency Disorders",
    "DNA Virus Infections",
    "Dacryocystitis",
    "Dandruff",
    "Dandy-Walker Syndrome",
    "Darier Disease",
    "De Lange Syndrome",
    "De Quervain Disease",
    "Deaf-Blind Disorders",
    "Deafness",
    "Decalcification, Pathologic",
    "Decompression Sickness",
    "Deficiency Diseases",
    "Deglutition Disorders",
    "Dehydration",
    "Deltaretrovirus Infections",
    "Dementia, Multi-Infarct",
    "Dementia, Vascular",
    "Demyelinating Autoimmune Diseases, CNS",
    "Demyelinating Diseases",
    "Dengue",
    "Dent Disease",
    "Dental Caries",
    "Dental Enamel Hypomineralization",
    "Dental Enamel Hypoplasia",
    "Dental Plaque",
    "Dental Pulp Calcification",
    "Dental Pulp Diseases",
    "Dental Pulp Exposure",
    "Dental Pulp Necrosis",
    "Dentigerous Cyst",
    "Dentin Dysplasia",
    "Dentin Sensitivity",
    "Dentinogenesis Imperfecta",
    "Dermatitis",
    "Dermatitis Herpetiformis",
    "Dermatitis, Allergic Contact",
    "Dermatitis, Atopic",
    "Dermatitis, Contact",
    "Dermatitis, Irritant",
    "Dermatitis, Occupational",
    "Dermatitis, Perioral",
    "Dermatitis, Photoallergic",
    "Dermatitis, Phototoxic",
    "Dermatitis, Seborrheic",
    "Dermatitis, Toxicodendron",
    "Dermatomycoses",
    "Dermatomyositis",
    "Desulfovibrionaceae Infections",
    "Developmental Defects of Enamel",
    "Developmental Dysplasia of the Hip",
    "DiGeorge Syndrome",
    "Diabesity",
    "Diabetes Complications",
    "Diabetes Insipidus",
    "Diabetes Insipidus, Nephrogenic",
    "Diabetes Insipidus, Neurogenic",
    "Diabetes Mellitus",
    "Diabetes Mellitus, Lipoatrophic",
    "Diabetes Mellitus, Type 1",
    "Diabetes Mellitus, Type 2",
    "Diabetes, Gestational",
    "Diabetic Angiopathies",
    "Diabetic Cardiomyopathies",
    "Diabetic Coma",
    "Diabetic Foot",
    "Diabetic Ketoacidosis",
    "Diabetic Nephropathies",
    "Diabetic Neuropathies",
    "Diabetic Retinopathy",
    "Diabulimia",
    "Diaper Rash",
    "Diaphragmatic Eventration",
    "Diaschisis",
    "Diastema",
    "Dicrocoeliasis",
    "Dictyocaulus Infections",
    "Dientamoebiasis",
    "Diffuse Cerebral Sclerosis of Schilder",
    "Digestive System Abnormalities",
    "Digestive System Diseases",
    "Digital Dermatitis",
    "Dipetalonema Infections",
    "Diphtheria",
    "Diphyllobothriasis",
    "Diplopia",
    "Dirofilariasis",
    "Discitis",
    "Discrete Subaortic Stenosis",
    "Disease",
    "Disease Attributes",
    "Diseases in Twins",
    "Disorder of Sex Development, 46,XY",
    "Disorders of Environmental Origin",
    "Disorders of Excessive Somnolence",
    "Disorders of Sex Development",
    "Dissection, Abdominal Aorta",
    "Dissection, Ascending Aorta",
    "Dissection, Blood Vessel",
    "Dissection, Thoracic Aorta",
    "Disseminated Intravascular Coagulation",
    "Distal Myopathies",
    "Distemper",
    "Diurnal Enuresis",
    "Diverticular Diseases",
    "Diverticulitis",
    "Diverticulitis, Colonic",
    "Diverticulosis, Colonic",
    "Diverticulosis, Esophageal",
    "Diverticulosis, Stomach",
    "Dog Diseases",
    "Donohue Syndrome",
    "Dourine",
    "Dracunculiasis",
    "Dropped Head Syndrome",
    "Drug Eruptions",
    "Drug Fever",
    "Drug Hypersensitivity",
    "Drug Hypersensitivity Syndrome",
    "Drug Resistant Epilepsy",
    "Drug-Related Side Effects and Adverse Reactions",
    "Dry Eye Syndromes",
    "Dry Socket",
    "Duane Retraction Syndrome",
    "Dumping Syndrome",
    "Duodenal Diseases",
    "Duodenal Obstruction",
    "Duodenal Ulcer",
    "Duodenitis",
    "Duodenogastric Reflux",
    "Dupuytren Contracture",
    "Dust Mite Allergy",
    "Dwarfism",
    "Dwarfism, Pituitary",
    "Dysarthria",
    "Dysautonomia, Familial",
    "Dysentery",
    "Dysentery, Amebic",
    "Dysentery, Bacillary",
    "Dysgammaglobulinemia",
    "Dyskeratosis Congenita",
    "Dyskinesia, Drug-Induced",
    "Dyslipidemias",
    "Dysostoses",
    "Dyspareunia",
    "Dyssomnias",
    "Dystocia",
    "Dystonia Musculorum Deformans",
    "Dystonic Disorders",
    "Ear Diseases",
    "Echinococcosis",
    "Echinococcosis, Hepatic",
    "Echinococcosis, Pulmonary",
    "Echinostomiasis",
    "Echovirus Infections",
    "Eclampsia",
    "Ecthyma",
    "Ecthyma, Contagious",
    "Ectodermal Dysplasia",
    "Ectodermal Dysplasia 1, Anhidrotic",
    "Ectodermal Dysplasia 3, Anhidrotic",
    "Ectodermal Dysplasia, Hypohidrotic, Autosomal Recessive",
    "Ectoparasitic Infestations",
    "Ectromelia, Infectious",
    "Ectropion",
    "Eczema",
    "Eczema, Dyshidrotic",
    "Edema Disease of Swine",
    "Edema, Cardiac",
    "Egg Hypersensitivity",
    "Ehlers-Danlos Syndrome",
    "Ehlers-Danlos Syndrome, Type IV",
    "Ehrlichiosis",
    "Ejaculatory Dysfunction",
    "Elbow Tendinopathy",
    "Elephantiasis",
    "Elephantiasis, Filarial",
    "Elliptocytosis, Hereditary",
    "Ellis-Van Creveld Syndrome",
    "Embolic Stroke",
    "Embolism",
    "Embolism and Thrombosis",
    "Embolism, Air",
    "Embolism, Amniotic Fluid",
    "Embolism, Cholesterol",
    "Embolism, Fat",
    "Embolism, Paradoxical",
    "Emphysematous Cholecystitis",
    "Emphysematous Pyelonephritis",
    "Empty Sella Syndrome",
    "Empyema, Pleural",
    "Empyema, Subdural",
    "Empyema, Tuberculous",
    "Encephalitis",
    "Encephalitis, Arbovirus",
    "Encephalitis, California",
    "Encephalitis, Herpes Simplex",
    "Encephalitis, Japanese",
    "Encephalitis, St. Louis",
    "Encephalitis, Tick-Borne",
    "Encephalitis, Varicella Zoster",
    "Encephalitis, Viral",
    "Encephalitozoonosis",
    "Encephalomalacia",
    "Encephalomyelitis",
    "Encephalomyelitis, Acute Disseminated",
    "Encephalomyelitis, Eastern Equine",
    "Encephalomyelitis, Enzootic Porcine",
    "Encephalomyelitis, Equine",
    "Encephalomyelitis, Venezuelan Equine",
    "Encephalomyelitis, Western Equine",
    "Encephalopathy, Bovine Spongiform",
    "Enchondromatosis",
    "End Stage Liver Disease",
    "Endarteritis",
    "Endemic Diseases",
    "Endocardial Fibroelastosis",
    "Endocarditis",
    "Endocarditis, Bacterial",
    "Endocarditis, Non-Infective",
    "Endocarditis, Subacute Bacterial",
    "Endocrine System Diseases",
    "Endolymphatic Hydrops",
    "Endometrial Hyperplasia",
    "Endometriosis",
    "Endometritis",
    "Endomyocardial Fibrosis",
    "Endophthalmitis",
    "Enophthalmos",
    "Enoplida Infections",
    "Entamoebiasis",
    "Enteritis",
    "Enteritis, Transmissible, of Turkeys",
    "Enterobacteriaceae Infections",
    "Enterobiasis",
    "Enterocolitis",
    "Enterocolitis, Necrotizing",
    "Enterocolitis, Neutropenic",
    "Enterocolitis, Pseudomembranous",
    "Enterotoxemia",
    "Enterovirus Infections",
    "Enthesopathy",
    "Entropion",
    "Enuresis",
    "Environmental Illness",
    "Eosinophilia",
    "Eosinophilia-Myalgia Syndrome",
    "Eosinophilic Esophagitis",
    "Ephemeral Fever",
    "Epidermitis, Exudative, of Swine",
    "Epidermolysis Bullosa",
    "Epidermolysis Bullosa Acquisita",
    "Epidermolysis Bullosa Dystrophica",
    "Epidermolysis Bullosa Simplex",
    "Epidermolysis Bullosa, Junctional",
    "Epididymitis",
    "Epidural Abscess",
    "Epiglottitis",
    "Epilepsia Partialis Continua",
    "Epilepsies, Myoclonic",
    "Epilepsies, Partial",
    "Epilepsy",
    "Epilepsy, Absence",
    "Epilepsy, Benign Neonatal",
    "Epilepsy, Complex Partial",
    "Epilepsy, Frontal Lobe",
    "Epilepsy, Generalized",
    "Epilepsy, Partial, Motor",
    "Epilepsy, Partial, Sensory",
    "Epilepsy, Reflex",
    "Epilepsy, Rolandic",
    "Epilepsy, Temporal Lobe",
    "Epilepsy, Tonic-Clonic",
    "Epileptic Syndromes",
    "Epiphyses, Slipped",
    "Epstein-Barr Virus Infections",
    "Equine Infectious Anemia",
    "Erdheim-Chester Disease",
    "Erectile Dysfunction",
    "Erysipelas",
    "Erysipeloid",
    "Erysipelothrix Infections",
    "Erythema Chronicum Migrans",
    "Erythema Induratum",
    "Erythema Infectiosum",
    "Erythema Multiforme",
    "Erythema Nodosum",
    "Erythrasma",
    "Erythroblastosis, Fetal",
    "Erythrokeratodermia Variabilis",
    "Erythromelalgia",
    "Escherichia coli Infections",
    "Esophageal Achalasia",
    "Esophageal Atresia",
    "Esophageal Diseases",
    "Esophageal Motility Disorders",
    "Esophageal Perforation",
    "Esophageal Spasm, Diffuse",
    "Esophageal Stenosis",
    "Esophagitis",
    "Esophagitis, Peptic",
    "Esotropia",
    "Essential Hypertension",
    "Essential Tremor",
    "Ethmoid Sinusitis",
    "Euglenozoa Infections",
    "Eunuchism",
    "Euthyroid Sick Syndromes",
    "Exanthema",
    "Exanthema Subitum",
    "Exercise-Induced Allergies",
    "Exfoliation Syndrome",
    "Exocrine Pancreatic Insufficiency",
    "Exophthalmos",
    "Exotropia",
    "Extensively Drug-Resistant Tuberculosis",
    "Eye Abnormalities",
    "Eye Diseases",
    "Eye Diseases, Hereditary",
    "Eye Infections",
    "Eye Infections, Bacterial",
    "Eye Infections, Fungal",
    "Eye Infections, Parasitic",
    "Eye Infections, Viral",
    "Eyelid Diseases",
    "Fabry Disease",
    "Facial Dermatoses",
    "Facial Hemiatrophy",
    "Facial Nerve Diseases",
    "Facial Neuralgia",
    "Factor V Deficiency",
    "Factor VII Deficiency",
    "Factor X Deficiency",
    "Factor XI Deficiency",
    "Factor XII Deficiency",
    "Factor XIII Deficiency",
    "Failure to Thrive",
    "Fallopian Tube Diseases",
    "Familial Exudative Vitreoretinopathies",
    "Familial Hypophosphatemic Rickets",
    "Familial Mediterranean Fever",
    "Familial Multiple Lipomatosis",
    "Familial Primary Pulmonary Hypertension",
    "Fanconi Anemia",
    "Fanconi Syndrome",
    "Farber Lipogranulomatosis",
    "Farmer's Lung",
    "Fasciitis",
    "Fasciitis, Necrotizing",
    "Fasciitis, Plantar",
    "Fascioliasis",
    "Fascioloidiasis",
    "Fatigue Syndrome, Chronic",
    "Fatty Liver",
    "Fatty Liver, Alcoholic",
    "Favism",
    "Febrile Neutropenia",
    "Fecal Incontinence",
    "Feline Acquired Immunodeficiency Syndrome",
    "Feline Infectious Peritonitis",
    "Feline Panleukopenia",
    "Felty Syndrome",
    "Female Athlete Triad Syndrome",
    "Female Urogenital Diseases",
    "Female Urogenital Diseases and Pregnancy Complications",
    "Feminization",
    "Femoral Neuropathy",
    "Femur Head Necrosis",
    "Fetal Alcohol Spectrum Disorders",
    "Fetal Diseases",
    "Fetal Hypoxia",
    "Fetal Membranes, Premature Rupture",
    "Fetal Nutrition Disorders",
    "Fetal Resorption",
    "Fetomaternal Transfusion",
    "Fibrocystic Breast Disease",
    "Fibromatosis, Plantar",
    "Fibromuscular Dysplasia",
    "Fibromyalgia",
    "Fibrous Dysplasia of Bone",
    "Fibrous Dysplasia, Polyostotic",
    "Filariasis",
    "Filoviridae Infections",
    "Fish Diseases",
    "Flail Chest",
    "Flaviviridae Infections",
    "Flavivirus Infections",
    "Flavobacteriaceae Infections",
    "Flea Infestations",
    "Fluorosis, Dental",
    "Focal Dermal Hypoplasia",
    "Focal Epithelial Hyperplasia",
    "Focal Facial Dermal Dysplasias",
    "Focal Infection",
    "Focal Nodular Hyperplasia",
    "Folic Acid Deficiency",
    "Folliculitis",
    "Food Hypersensitivity",
    "Foodborne Diseases",
    "Foot Deformities, Congenital",
    "Foot Dermatoses",
    "Foot Diseases",
    "Foot Rot",
    "Foot Ulcer",
    "Foot-and-Mouth Disease",
    "Foramen Ovale, Patent",
    "Fournier Gangrene",
    "Fowlpox",
    "Fox-Fordyce Disease",
    "Fractures, Spontaneous",
    "Fraser Syndrome",
    "Frasier Syndrome",
    "Freemartinism",
    "Friedreich Ataxia",
    "Frontal Sinusitis",
    "Fructose Intolerance",
    "Fructose Metabolism, Inborn Errors",
    "Fructose-1,6-Diphosphatase Deficiency",
    "Fuchs' Endothelial Dystrophy",
    "Fucosidosis",
    "Fungemia",
    "Furunculosis",
    "Fusariosis",
    "Fusobacteriaceae Infections",
    "Fusobacterium Infections",
    "GATA2 Deficiency",
    "Gait Disorders, Neurologic",
    "Galactorrhea",
    "Galactosemias",
    "Gallbladder Diseases",
    "Gangliosidoses",
    "Gangliosidoses, GM2",
    "Gangliosidosis, GM1",
    "Gangrene",
    "Gas Gangrene",
    "Gastric Antral Vascular Ectasia",
    "Gastric Dilatation",
    "Gastric Outlet Obstruction",
    "Gastritis",
    "Gastritis, Atrophic",
    "Gastritis, Hypertrophic",
    "Gastroenteritis",
    "Gastroenteritis, Transmissible, of Swine",
    "Gastroesophageal Reflux",
    "Gastrointestinal Diseases",
    "Gastroparesis",
    "Gastroschisis",
    "Gaucher Disease",
    "General Adaptation Syndrome",
    "Genetic Diseases, Inborn",
    "Genetic Diseases, X-Linked",
    "Genetic Diseases, Y-Linked",
    "Genital Diseases",
    "Genital Diseases, Female",
    "Genital Diseases, Male",
    "Genu Valgum",
    "Genu Varum",
    "Geographic Atrophy",
    "Geotrichosis",
    "Gerstmann Syndrome",
    "Gerstmann-Straussler-Scheinker Disease",
    "Giant Axonal Neuropathy",
    "Giant Cell Arteritis",
    "Giant Cell Tumor of Tendon Sheath",
    "Giardiasis",
    "Gigantism",
    "Gilbert Disease",
    "Gingival Diseases",
    "Gingival Hyperplasia",
    "Gingival Hypertrophy",
    "Gingival Overgrowth",
    "Gingival Recession",
    "Gingivitis",
    "Gingivitis, Necrotizing Ulcerative",
    "Gitelman Syndrome",
    "Glanders",
    "Glaucoma",
    "Glaucoma, Angle-Closure",
    "Glaucoma, Neovascular",
    "Glaucoma, Open-Angle",
    "Globus Sensation",
    "Glomerulonephritis",
    "Glomerulonephritis, IGA",
    "Glomerulonephritis, Membranoproliferative",
    "Glomerulonephritis, Membranous",
    "Glomerulosclerosis, Focal Segmental",
    "Glossitis",
    "Glossitis, Benign Migratory",
    "Glossopharyngeal Nerve Diseases",
    "Glucose Intolerance",
    "Glucose Metabolism Disorders",
    "Glucosephosphate Dehydrogenase Deficiency",
    "Glycogen Storage Disease",
    "Glycogen Storage Disease Type I",
    "Glycogen Storage Disease Type II",
    "Glycogen Storage Disease Type III",
    "Glycogen Storage Disease Type IIb",
    "Glycogen Storage Disease Type IV",
    "Glycogen Storage Disease Type V",
    "Glycogen Storage Disease Type VI",
    "Glycogen Storage Disease Type VII",
    "Glycogen Storage Disease Type VIII",
    "Glycosuria",
    "Glycosuria, Renal",
    "Gnathostomiasis",
    "Goat Diseases",
    "Goiter",
    "Goiter, Endemic",
    "Goiter, Nodular",
    "Goiter, Substernal",
    "Goldenhar Syndrome",
    "Gonadal Disorders",
    "Gonadal Dysgenesis",
    "Gonadal Dysgenesis, 46,XX",
    "Gonadal Dysgenesis, 46,XY",
    "Gonadal Dysgenesis, Mixed",
    "Gonorrhea",
    "Gout",
    "Graft vs Host Disease",
    "Gram-Negative Bacterial Infections",
    "Gram-Positive Bacterial Infections",
    "Granuloma Annulare",
    "Granuloma Inguinale",
    "Granuloma, Lethal Midline",
    "Granuloma, Pyogenic",
    "Granulomatosis with Polyangiitis",
    "Granulomatosis, Orofacial",
    "Granulomatous Disease, Chronic",
    "Granulomatous Mastitis",
    "Graves Disease",
    "Graves Ophthalmopathy",
    "Gray Platelet Syndrome",
    "Guillain-Barre Syndrome",
    "Guttate Psoriasis",
    "Gynatresia",
    "Gynecomastia",
    "Gyrate Atrophy",
    "HELLP Syndrome",
    "HIV Enteropathy",
    "HIV Infections",
    "HIV Wasting Syndrome",
    "HIV-Associated Lipodystrophy Syndrome",
    "HTLV-I Infections",
    "HTLV-II Infections",
    "Haemonchiasis",
    "Haemophilus Infections",
    "Hair Diseases",
    "Hajdu-Cheney Syndrome",
    "Hamartoma",
    "Hamman-Rich Syndrome",
    "Hand Dermatoses",
    "Hand, Foot and Mouth Disease",
    "Hand-Arm Vibration Syndrome",
    "Hand-Foot Syndrome",
    "Hantavirus Infections",
    "Hantavirus Pulmonary Syndrome",
    "Hartnup Disease",
    "Hashimoto Disease",
    "Headache Disorders",
    "Headache Disorders, Primary",
    "Headache Disorders, Secondary",
    "Healthcare-Associated Pneumonia",
    "Hearing Disorders",
    "Hearing Loss, Bilateral",
    "Hearing Loss, Central",
    "Hearing Loss, Conductive",
    "Hearing Loss, High-Frequency",
    "Hearing Loss, Mixed Conductive-Sensorineural",
    "Hearing Loss, Sensorineural",
    "Hearing Loss, Sudden",
    "Hearing Loss, Unilateral",
    "Heart Aneurysm",
    "Heart Block",
    "Heart Defects, Congenital",
    "Heart Diseases",
    "Heart Failure",
    "Heart Failure, Diastolic",
    "Heart Failure, Systolic",
    "Heart Rupture",
    "Heart Rupture, Post-Infarction",
    "Heart Septal Defects",
    "Heart Septal Defects, Ventricular",
    "Heart Valve Diseases",
    "Heart Valve Prolapse",
    "Heartwater Disease",
    "Heavy Chain Disease",
    "Heel Spur",
    "Helicobacter Infections",
    "Helminthiasis",
    "Helminthiasis, Animal",
    "Hematologic Diseases",
    "Hematometra",
    "Hemic and Lymphatic Diseases",
    "Hemimegalencephaly",
    "Hemochromatosis",
    "Hemoglobin C Disease",
    "Hemoglobin SC Disease",
    "Hemoglobinopathies",
    "Hemoglobinuria",
    "Hemoglobinuria, Paroxysmal",
    "Hemolytic-Uremic Syndrome",
    "Hemophilia A",
    "Hemophilia B",
    "Hemorrhagic Disorders",
    "Hemorrhagic Fever with Renal Syndrome",
    "Hemorrhagic Fever, American",
    "Hemorrhagic Fever, Crimean",
    "Hemorrhagic Fever, Ebola",
    "Hemorrhagic Fever, Omsk",
    "Hemorrhagic Fevers, Viral",
    "Hemorrhagic Septicemia",
    "Hemorrhagic Septicemia, Viral",
    "Hemorrhagic Stroke",
    "Hemorrhagic Syndrome, Bovine",
    "Hemorrhoids",
    "Hemosiderosis",
    "Hemosiderosis, Pulmonary",
    "Hemospermia",
    "Hemostatic Disorders",
    "Henipavirus Infections",
    "Hepadnaviridae Infections",
    "Hepatic Encephalopathy",
    "Hepatic Infarction",
    "Hepatic Veno-Occlusive Disease",
    "Hepatitis",
    "Hepatitis A",
    "Hepatitis B",
    "Hepatitis B, Chronic",
    "Hepatitis C",
    "Hepatitis C, Chronic",
    "Hepatitis D",
    "Hepatitis D, Chronic",
    "Hepatitis E",
    "Hepatitis, Alcoholic",
    "Hepatitis, Animal",
    "Hepatitis, Autoimmune",
    "Hepatitis, Chronic",
    "Hepatitis, Infectious Canine",
    "Hepatitis, Viral, Animal",
    "Hepatitis, Viral, Human",
    "Hepatolenticular Degeneration",
    "Hepatopulmonary Syndrome",
    "Hepatorenal Syndrome",
    "Hereditary Angioedema Types I and II",
    "Hereditary Autoinflammatory Diseases",
    "Hereditary Central Nervous System Demyelinating Diseases",
    "Hereditary Complement Deficiency Diseases",
    "Hereditary Sensory and Autonomic Neuropathies",
    "Hereditary Sensory and Motor Neuropathy",
    "Heredodegenerative Disorders, Nervous System",
    "Hermanski-Pudlak Syndrome",
    "Hernia, Abdominal",
    "Hernia, Diaphragmatic",
    "Hernia, Femoral",
    "Hernia, Hiatal",
    "Hernia, Inguinal",
    "Hernia, Umbilical",
    "Hernia, Ventral",
    "Herpangina",
    "Herpes Genitalis",
    "Herpes Labialis",
    "Herpes Simplex",
    "Herpes Zoster",
    "Herpes Zoster Ophthalmicus",
    "Herpes Zoster Oticus",
    "Herpesviridae Infections",
    "Heterotaxy Syndrome",
    "Hidradenitis",
    "Hidradenitis Suppurativa",
    "High Pressure Neurological Syndrome",
    "Hip Contracture",
    "Hip Dislocation, Congenital",
    "Hip Dysplasia, Canine",
    "Hippocampal Sclerosis",
    "Histiocytic Necrotizing Lymphadenitis",
    "Histiocytosis",
    "Histiocytosis, Langerhans-Cell",
    "Histiocytosis, Non-Langerhans-Cell",
    "Histiocytosis, Sinus",
    "Histoplasmosis",
    "Holocarboxylase Synthetase Deficiency",
    "Homocystinuria",
    "Homozygous Familial Hypercholesterolemia",
    "Hookworm Infections",
    "Hordeolum",
    "Horner Syndrome",
    "Horse Diseases",
    "Huntington Disease",
    "Hyaline Fibromatosis Syndrome",
    "Hyalohyphomycosis",
    "Hydrarthrosis",
    "Hydroa Vacciniforme",
    "Hydrocephalus",
    "Hydrocephalus, Normal Pressure",
    "Hydronephrosis",
    "Hydrophthalmos",
    "Hydropneumothorax",
    "Hydrothorax",
    "Hymenolepiasis",
    "Hyper-IgM Immunodeficiency Syndrome",
    "Hyper-IgM Immunodeficiency Syndrome, Type 1",
    "Hyperaldosteronism",
    "Hyperalgesia",
    "Hyperandrogenism",
    "Hyperargininemia",
    "Hyperbilirubinemia, Hereditary",
    "Hyperbilirubinemia, Neonatal",
    "Hypercalcemia",
    "Hypercementosis",
    "Hypercholesterolemia",
    "Hyperekplexia",
    "Hyperemia",
    "Hypereosinophilic Syndrome",
    "Hypergammaglobulinemia",
    "Hyperglycemia",
    "Hyperglycemic Hyperosmolar Nonketotic Coma",
    "Hyperglycinemia, Nonketotic",
    "Hyperhidrosis",
    "Hyperhomocysteinemia",
    "Hyperinsulinism",
    "Hyperkeratosis, Epidermolytic",
    "Hyperlipidemia, Familial Combined",
    "Hyperlipidemias",
    "Hyperlipoproteinemia Type I",
    "Hyperlipoproteinemia Type II",
    "Hyperlipoproteinemia Type III",
    "Hyperlipoproteinemia Type IV",
    "Hyperlipoproteinemia Type V",
    "Hyperlipoproteinemias",
    "Hyperlysinemias",
    "Hypernatremia",
    "Hyperopia",
    "Hyperostosis",
    "Hyperostosis Frontalis Interna",
    "Hyperostosis, Cortical, Congenital",
    "Hyperostosis, Diffuse Idiopathic Skeletal",
    "Hyperostosis, Sternocostoclavicular",
    "Hyperoxaluria",
    "Hyperoxaluria, Primary",
    "Hyperparathyroidism",
    "Hyperparathyroidism, Primary",
    "Hyperparathyroidism, Secondary",
    "Hyperphosphatemia",
    "Hyperpituitarism",
    "Hyperprolactinemia",
    "Hypersplenism",
    "Hypertension",
    "Hypertension, Malignant",
    "Hypertension, Portal",
    "Hypertension, Pregnancy-Induced",
    "Hypertension, Pulmonary",
    "Hypertension, Renal",
    "Hypertension, Renovascular",
    "Hypertensive Crisis",
    "Hypertensive Encephalopathy",
    "Hypertensive Retinopathy",
    "Hyperthyroidism",
    "Hyperthyroxinemia",
    "Hyperthyroxinemia, Familial Dysalbuminemic",
    "Hypertrichosis",
    "Hypertriglyceridemia",
    "Hypervitaminosis A",
    "Hypoadrenocorticism, Familial",
    "Hypoaldosteronism",
    "Hypoalphalipoproteinemias",
    "Hypobetalipoproteinemia, Familial, Apolipoprotein B",
    "Hypobetalipoproteinemias",
    "Hypocalcemia",
    "Hypodermyiasis",
    "Hypoglossal Nerve Diseases",
    "Hypoglycemia",
    "Hypogonadism",
    "Hypohidrosis",
    "Hypokalemia",
    "Hypokalemic Periodic Paralysis",
    "Hypolipoproteinemias",
    "Hyponatremia",
    "Hypoparathyroidism",
    "Hypophosphatasia",
    "Hypophosphatemia",
    "Hypophosphatemia, Familial",
    "Hypophysitis",
    "Hypopigmentation",
    "Hypopituitarism",
    "Hypoplastic Left Heart Syndrome",
    "Hypoprothrombinemias",
    "Hypothalamic Diseases",
    "Hypothyroidism",
    "Hypotrichosis",
    "Hypoxia-Ischemia, Brain",
    "Iatrogenic Disease",
    "Ichthyosiform Erythroderma, Congenital",
    "Ichthyosis",
    "Ichthyosis Bullosa of Siemens",
    "Ichthyosis Vulgaris",
    "Ichthyosis, Lamellar",
    "Ichthyosis, X-Linked",
    "Idiopathic Hypersomnia",
    "Idiopathic Interstitial Pneumonias",
    "Idiopathic Noncirrhotic Portal Hypertension",
    "Idiopathic Pulmonary Fibrosis",
    "IgA Deficiency",
    "IgA Vasculitis",
    "IgG Deficiency",
    "Ileal Diseases",
    "Ileitis",
    "Ileus",
    "Iliac Aneurysm",
    "Iliotibial Band Syndrome",
    "Immune Complex Diseases",
    "Immune Reconstitution Inflammatory Syndrome",
    "Immune System Diseases",
    "Immunoblastic Lymphadenopathy",
    "Immunoglobulin G4-Related Disease",
    "Immunoglobulin Light-chain Amyloidosis",
    "Immunologic Deficiency Syndromes",
    "Immunoproliferative Disorders",
    "Impetigo",
    "Impotence, Vasculogenic",
    "Imprinting Disorders",
    "Inappropriate ADH Syndrome",
    "Incisional Hernia",
    "Incontinentia Pigmenti",
    "Infant Nutrition Disorders",
    "Infant, Newborn, Diseases",
    "Infant, Premature, Diseases",
    "Infarction",
    "Infarction, Anterior Cerebral Artery",
    "Infarction, Middle Cerebral Artery",
    "Infarction, Posterior Cerebral Artery",
    "Infections",
    "Infectious Bovine Rhinotracheitis",
    "Infectious Encephalitis",
    "Infectious Mononucleosis",
    "Inferior Wall Myocardial Infarction",
    "Inflammatory Bowel Diseases",
    "Influenza in Birds",
    "Influenza, Human",
    "Insomnia, Fatal Familial",
    "Insulin Coma",
    "Interatrial Block",
    "Intermittent Claudication",
    "Intertrigo",
    "Intervertebral Disc Degeneration",
    "Intervertebral Disc Displacement",
    "Intestinal Atresia",
    "Intestinal Diseases",
    "Intestinal Diseases, Parasitic",
    "Intestinal Failure",
    "Intestinal Obstruction",
    "Intestinal Perforation",
    "Intestinal Polyposis",
    "Intestinal Pseudo-Obstruction",
    "Intestinal Volvulus",
    "Intra-Abdominal Hypertension",
    "Intraabdominal Infections",
    "Intracranial Aneurysm",
    "Intracranial Arterial Diseases",
    "Intracranial Arteriosclerosis",
    "Intracranial Embolism",
    "Intracranial Embolism and Thrombosis",
    "Intracranial Hypertension",
    "Intracranial Hypotension",
    "Intracranial Thrombosis",
    "Intussusception",
    "Invasive Fungal Infections",
    "Invasive Pulmonary Aspergillosis",
    "Iridocorneal Endothelial Syndrome",
    "Iridocyclitis",
    "Iris Diseases",
    "Iritis",
    "Iron Metabolism Disorders",
    "Iron Overload",
    "Irritable Bowel Syndrome",
    "Isaacs Syndrome",
    "Ischemic Attack, Transient",
    "Ischemic Contracture",
    "Ischemic Stroke",
    "Isolated Noncompaction of the Ventricular Myocardium",
    "Isolated Systolic Hypertension",
    "Isosporiasis",
    "Jacobsen Distal 11q Deletion Syndrome",
    "Jaundice, Chronic Idiopathic",
    "Jaw Abnormalities",
    "Jaw Cysts",
    "Jaw Diseases",
    "Jaw, Edentulous",
    "Jaw, Edentulous, Partially",
    "Jejunal Diseases",
    "Jervell-Lange Nielsen Syndrome",
    "Jet Lag Syndrome",
    "Job Syndrome",
    "Joint Diseases",
    "Joint Instability",
    "Kallmann Syndrome",
    "Kaposi Varicelliform Eruption",
    "Kartagener Syndrome",
    "Kasabach-Merritt Syndrome",
    "Kashin-Beck Disease",
    "Kearns-Sayre Syndrome",
    "Keloid",
    "Keratitis",
    "Keratitis, Dendritic",
    "Keratitis, Herpetic",
    "Keratoacanthoma",
    "Keratoconjunctivitis",
    "Keratoconjunctivitis Sicca",
    "Keratoconjunctivitis, Infectious",
    "Keratoconus",
    "Keratoderma, Palmoplantar",
    "Keratoderma, Palmoplantar, Diffuse",
    "Keratoderma, Palmoplantar, Epidermolytic",
    "Keratosis, Actinic",
    "Kernicterus",
    "Ketosis",
    "Kidney Cortex Necrosis",
    "Kidney Diseases",
    "Kidney Diseases, Cystic",
    "Kidney Failure, Chronic",
    "Kidney Papillary Necrosis",
    "Kidney Tubular Necrosis, Acute",
    "Kimura Disease",
    "King's Evil",
    "Klebsiella Infections",
    "Kleine-Levin Syndrome",
    "Klinefelter Syndrome",
    "Klippel-Trenaunay-Weber Syndrome",
    "Kounis Syndrome",
    "Kuru",
    "Kwashiorkor",
    "Kyasanur Forest Disease",
    "LEOPARD Syndrome",
    "Laboratory Infection",
    "Labyrinth Diseases",
    "Labyrinthitis",
    "Lacrimal Apparatus Diseases",
    "Lactation Disorders",
    "Lactose Intolerance",
    "Lafora Disease",
    "Lambert-Eaton Myasthenic Syndrome",
    "Laminopathies",
    "Langer-Giedion Syndrome",
    "Larva Migrans",
    "Larva Migrans, Visceral",
    "Laryngeal Diseases",
    "Laryngismus",
    "Laryngitis",
    "Laryngomalacia",
    "Laryngopharyngeal Reflux",
    "Laryngostenosis",
    "Lassa Fever",
    "Late Onset Disorders",
    "Latent Autoimmune Diabetes in Adults",
    "Latent Infection",
    "Latent Tuberculosis",
    "Lateral Medullary Syndrome",
    "Lateral Sinus Thrombosis",
    "Latex Hypersensitivity",
    "Laurence-Moon Syndrome",
    "Leber Congenital Amaurosis",
    "Lecithin Cholesterol Acyltransferase Deficiency",
    "Leg Dermatoses",
    "Leg Length Inequality",
    "Leg Ulcer",
    "Legg-Calve-Perthes Disease",
    "Legionellosis",
    "Legionnaires' Disease",
    "Leigh Disease",
    "Leishmaniasis",
    "Leishmaniasis, Cutaneous",
    "Leishmaniasis, Diffuse Cutaneous",
    "Leishmaniasis, Mucocutaneous",
    "Leishmaniasis, Visceral",
    "Lemierre Syndrome",
    "Lennox Gastaut Syndrome",
    "Lens Diseases",
    "Lens Subluxation",
    "Lentigo",
    "Lentivirus Infections",
    "Leprosy",
    "Leprosy, Borderline",
    "Leprosy, Lepromatous",
    "Leprosy, Multibacillary",
    "Leprosy, Paucibacillary",
    "Leprosy, Tuberculoid",
    "Leptospirosis",
    "Leriche Syndrome",
    "Lesch-Nyhan Syndrome",
    "Leukemoid Reaction",
    "Leukocyte Disorders",
    "Leukocyte-Adhesion Deficiency Syndrome",
    "Leukodystrophy, Globoid Cell",
    "Leukodystrophy, Metachromatic",
    "Leukoedema, Oral",
    "Leukoencephalitis, Acute Hemorrhagic",
    "Leukoencephalopathies",
    "Leukoencephalopathy, Progressive Multifocal",
    "Leukokeratosis, Hereditary Mucosal",
    "Leukomalacia, Periventricular",
    "Leukorrhea",
    "Leukostasis",
    "Lewy Body Disease",
    "Lice Infestations",
    "Lichen Nitidus",
    "Lichen Planus",
    "Lichen Planus, Oral",
    "Lichen Sclerosus et Atrophicus",
    "Lichenoid Eruptions",
    "Liddle Syndrome",
    "Limbal Stem Cell Deficiency",
    "Limbic Encephalitis",
    "Linear IgA Bullous Dermatosis",
    "Lingual Goiter",
    "Lingual Thyroid",
    "Lip Diseases",
    "Lipedema",
    "Lipid Metabolism Disorders",
    "Lipid Metabolism, Inborn Errors",
    "Lipidoses",
    "Lipodystrophy",
    "Lipodystrophy, Congenital Generalized",
    "Lipodystrophy, Familial Partial",
    "Lipoid Proteinosis of Urbach and Wiethe",
    "Lipomatosis",
    "Lipomatosis, Multiple Symmetrical",
    "Lissencephaly",
    "Listeriosis",
    "Livedoid Vasculopathy",
    "Liver Abscess",
    "Liver Abscess, Amebic",
    "Liver Abscess, Pyogenic",
    "Liver Cirrhosis",
    "Liver Cirrhosis, Alcoholic",
    "Liver Cirrhosis, Biliary",
    "Liver Diseases",
    "Liver Diseases, Alcoholic",
    "Liver Diseases, Parasitic",
    "Liver Failure, Acute",
    "Lobomycosis",
    "Locked-In Syndrome",
    "Loeys-Dietz Syndrome",
    "Loiasis",
    "Long QT Syndrome",
    "Loose Anagen Hair Syndrome",
    "Louping Ill",
    "Low Anterior Resection Syndrome",
    "Low Tension Glaucoma",
    "Lown-Ganong-Levine Syndrome",
    "Ludwig's Angina",
    "Lumpy Skin Disease",
    "Lung Abscess",
    "Lung Diseases",
    "Lung Diseases, Fungal",
    "Lung Diseases, Interstitial",
    "Lung Diseases, Obstructive",
    "Lung Diseases, Parasitic",
    "Lung, Hyperlucent",
    "Lupus Erythematosus, Cutaneous",
    "Lupus Erythematosus, Discoid",
    "Lupus Erythematosus, Systemic",
    "Lupus Nephritis",
    "Lupus Vasculitis, Central Nervous System",
    "Lupus Vulgaris",
    "Lutembacher Syndrome",
    "Lyme Disease",
    "Lyme Neuroborreliosis",
    "Lymphangiectasis",
    "Lymphangitis",
    "Lymphatic Diseases",
    "Lymphedema",
    "Lymphocele",
    "Lymphocytic Choriomeningitis",
    "Lymphocytosis",
    "Lymphogranuloma Venereum",
    "Lymphohistiocytosis, Hemophagocytic",
    "Lymphoma, Mantle-Cell",
    "Lymphopenia",
    "Lymphoproliferative Disorders",
    "Lysosomal Storage Diseases",
    "Lysosomal Storage Diseases, Nervous System",
    "MELAS Syndrome",
    "MERRF Syndrome",
    "MINOCA",
    "Machado-Joseph Disease",
    "Macrophage Activation Syndrome",
    "Macular Degeneration",
    "Macular Edema",
    "Magnesium Deficiency",
    "Malabsorption Syndromes",
    "Malaria",
    "Malaria, Avian",
    "Malaria, Cerebral",
    "Malaria, Falciparum",
    "Malaria, Vivax",
    "Male Urogenital Diseases",
    "Malformations of Cortical Development",
    "Malformations of Cortical Development, Group I",
    "Malformations of Cortical Development, Group II",
    "Malformations of Cortical Development, Group III",
    "Malignant Atrophic Papulosis",
    "Malignant Carcinoid Syndrome",
    "Malignant Catarrh",
    "Mallory-Weiss Syndrome",
    "Malnutrition",
    "Malocclusion, Angle Class I",
    "Malocclusion, Angle Class II",
    "Malocclusion, Angle Class III",
    "Mandibular Diseases",
    "Mannosidase Deficiency Diseases",
    "Mansonelliasis",
    "Maple Syrup Urine Disease",
    "Marburg Virus Disease",
    "Marchiafava-Bignami Disease",
    "Marfan Syndrome",
    "Mast Cell Activation Disorders",
    "Mast Cell Activation Syndrome",
    "Mastitis",
    "Mastitis, Bovine",
    "Mastocytosis",
    "Mastocytosis, Cutaneous",
    "Mastocytosis, Systemic",
    "Mastoiditis",
    "Maxillary Diseases",
    "Maxillary Sinusitis",
    "May-Thurner Syndrome",
    "Measles",
    "Meckel Diverticulum",
    "Meconium Aspiration Syndrome",
    "Medial Tibial Stress Syndrome",
    "Median Arcuate Ligament Syndrome",
    "Median Neuropathy",
    "Mediastinal Cyst",
    "Mediastinal Diseases",
    "Mediastinitis",
    "Medullary Sponge Kidney",
    "Megacolon",
    "Megacolon, Toxic",
    "Megalencephaly",
    "Meibomian Gland Dysfunction",
    "Meibomitis",
    "Meige Syndrome",
    "Melanoma, Cutaneous Malignant",
    "Melanosis",
    "Melioidosis",
    "Melkersson-Rosenthal Syndrome",
    "Melorheostosis",
    "Meniere Disease",
    "Meningeal Carcinomatosis",
    "Meningism",
    "Meningitis",
    "Meningitis, Aseptic",
    "Meningitis, Bacterial",
    "Meningitis, Cryptococcal",
    "Meningitis, Escherichia coli",
    "Meningitis, Fungal",
    "Meningitis, Haemophilus",
    "Meningitis, Listeria",
    "Meningitis, Meningococcal",
    "Meningitis, Pneumococcal",
    "Meningitis, Viral",
    "Meningococcal Infections",
    "Meningoencephalitis",
    "Menkes Kinky Hair Syndrome",
    "Menopause, Premature",
    "Mercury Poisoning",
    "Mesenteric Ischemia",
    "Mesenteric Lymphadenitis",
    "Mesenteric Vascular Occlusion",
    "Mesomycetozoea Infections",
    "Metabolic Diseases",
    "Metabolic Syndrome",
    "Metabolism, Inborn Errors",
    "Metal Metabolism, Inborn Errors",
    "Metatarsalgia",
    "Methemoglobinemia",
    "Mevalonate Kinase Deficiency",
    "Microaneurysm",
    "Microcephaly",
    "Microscopic Polyangiitis",
    "Microsporidiosis",
    "Microvascular Angina",
    "Middle Lobe Syndrome",
    "Migraine Disorders",
    "Migraine with Aura",
    "Migraine without Aura",
    "Mikulicz' Disease",
    "Miliaria",
    "Milk Hypersensitivity",
    "Miller Fisher Syndrome",
    "Mineralocorticoid Excess Syndrome, Apparent",
    "Mink Viral Enteritis",
    "Mirizzi Syndrome",
    "Mite Infestations",
    "Mitochondrial Diseases",
    "Mitochondrial Encephalomyopathies",
    "Mitochondrial Myopathies",
    "Mitral Valve Insufficiency",
    "Mitral Valve Prolapse",
    "Mitral Valve Stenosis",
    "Mixed Connective Tissue Disease",
    "Mixed Dementias",
    "Mobius Syndrome",
    "Molar Hypomineralization",
    "Molluscum Contagiosum",
    "Monieziasis",
    "Monilethrix",
    "Monkey Diseases",
    "Monoclonal Gammopathy of Undetermined Significance",
    "Mononegavirales Infections",
    "Mononeuropathies",
    "Morbillivirus Infections",
    "Morgellons Disease",
    "Morton Neuroma",
    "Mosquito-Borne Diseases",
    "Motor Neuron Disease",
    "Mouth Abnormalities",
    "Mouth Diseases",
    "Mouth, Edentulous",
    "Movement Disorders",
    "Moyamoya Disease",
    "Mpox, Monkeypox",
    "Mucinoses",
    "Mucinosis, Follicular",
    "Mucocutaneous Lymph Node Syndrome",
    "Mucolipidoses",
    "Mucopolysaccharidoses",
    "Mucopolysaccharidosis I",
    "Mucopolysaccharidosis II",
    "Mucopolysaccharidosis III",
    "Mucopolysaccharidosis IV",
    "Mucopolysaccharidosis VI",
    "Mucopolysaccharidosis VII",
    "Mucormycosis",
    "Mucositis",
    "Muir-Torre Syndrome",
    "Mulibrey Nanism",
    "Multicystic Dysplastic Kidney",
    "Multifocal Choroiditis",
    "Multiple Carboxylase Deficiency",
    "Multiple Chemical Sensitivity",
    "Multiple Chronic Conditions",
    "Multiple Sclerosis",
    "Multiple Sclerosis, Chronic Progressive",
    "Multiple Sclerosis, Relapsing-Remitting",
    "Multiple Sulfatase Deficiency Disease",
    "Multiple System Atrophy",
    "Mumps",
    "Muscular Atrophy",
    "Muscular Atrophy, Spinal",
    "Muscular Diseases",
    "Muscular Disorders, Atrophic",
    "Muscular Dystrophies",
    "Muscular Dystrophies, Limb-Girdle",
    "Muscular Dystrophy, Animal",
    "Muscular Dystrophy, Duchenne",
    "Muscular Dystrophy, Emery-Dreifuss",
    "Muscular Dystrophy, Facioscapulohumeral",
    "Muscular Dystrophy, Oculopharyngeal",
    "Musculoskeletal Abnormalities",
    "Musculoskeletal Diseases",
    "Mutism",
    "Myasthenia Gravis",
    "Myasthenia Gravis, Neonatal",
    "Myasthenic Syndromes, Congenital",
    "Mycetoma",
    "Mycobacterium Infections",
    "Mycobacterium Infections, Nontuberculous",
    "Mycobacterium avium-intracellulare Infection",
    "Mycoplasma Infections",
    "Mycoplasmatales Infections",
    "Mycoses",
    "Myelin Oligodendrocyte Glycoprotein Antibody-Associated Disease",
    "Myelinolysis, Central Pontine",
    "Myelitis",
    "Myelitis, Transverse",
    "Myiasis",
    "Myocardial Infarction",
    "Myocardial Ischemia",
    "Myocardial Stunning",
    "Myocarditis",
    "Myoclonic Cerebellar Dyssynergia",
    "Myoclonic Epilepsies, Progressive",
    "Myoclonic Epilepsy, Juvenile",
    "Myofascial Pain Syndromes",
    "Myopathies, Nemaline",
    "Myopathies, Structural, Congenital",
    "Myopathy, Central Core",
    "Myopia",
    "Myopia, Degenerative",
    "Myositis",
    "Myositis Ossificans",
    "Myositis, Inclusion Body",
    "Myotonia Congenita",
    "Myotonic Disorders",
    "Myotonic Dystrophy",
    "Myringosclerosis",
    "Myxedema",
    "Myxomatosis, Infectious",
    "Nail Diseases",
    "Nail-Patella Syndrome",
    "Nails, Ingrown",
    "Nails, Malformed",
    "Nairobi Sheep Disease",
    "Narcolepsy",
    "Nasal Obstruction",
    "Nasopharyngeal Diseases",
    "Nasopharyngitis",
    "Necatoriasis",
    "Necrobiosis Lipoidica",
    "Necrobiotic Xanthogranuloma",
    "Necrolytic Migratory Erythema",
    "Neglected Diseases",
    "Neisseriaceae Infections",
    "Nematode Infections",
    "Neointima",
    "Neonatal Abstinence Syndrome",
    "Neonatal Brachial Plexus Palsy",
    "Neonatal Sepsis",
    "Nephritis",
    "Nephritis, Hereditary",
    "Nephritis, Interstitial",
    "Nephrocalcinosis",
    "Nephrogenic Fibrosing Dermopathy",
    "Nephrolithiasis",
    "Nephrosclerosis",
    "Nephrosis",
    "Nephrosis, Lipoid",
    "Nephrotic Syndrome",
    "Nerve Compression Syndromes",
    "Nervous System Diseases",
    "Nervous System Malformations",
    "Nesidioblastosis",
    "Netherton Syndrome",
    "Neuritis",
    "Neuroacanthocytosis",
    "Neuroaspergillosis",
    "Neuroaxonal Dystrophies",
    "Neurocirculatory Asthenia",
    "Neurocysticercosis",
    "Neurodegenerative Diseases",
    "Neurodermatitis",
    "Neurofibromatosis 1",
    "Neurogenic Bowel",
    "Neuroinflammatory Diseases",
    "Neuroleptic Malignant Syndrome",
    "Neuromuscular Diseases",
    "Neuromuscular Junction Diseases",
    "Neuromyelitis Optica",
    "Neuronal Ceroid-Lipofuscinoses",
    "Neuroschistosomiasis",
    "Neurosyphilis",
    "Neutropenia",
    "Newcastle Disease",
    "Nicolau Syndrome",
    "Nidovirales Infections",
    "Niemann-Pick Disease, Type A",
    "Niemann-Pick Disease, Type B",
    "Niemann-Pick Disease, Type C",
    "Niemann-Pick Diseases",
    "Night Blindness",
    "Nijmegen Breakage Syndrome",
    "Nocardia Infections",
    "Nocturnal Enuresis",
    "Nocturnal Myoclonus Syndrome",
    "Nocturnal Paroxysmal Dystonia",
    "Nodding Syndrome",
    "Noma",
    "Non-Erosive Reflux Disease",
    "Non-Filarial Lymphedema",
    "Non-Radiographic Axial Spondyloarthritis",
    "Non-ST Elevated Myocardial Infarction",
    "Non-alcoholic Fatty Liver Disease",
    "Noncommunicable Diseases",
    "Nonodontogenic Cysts",
    "Noonan Syndrome",
    "Nose Diseases",
    "Nuchal Cord",
    "Nut Hypersensitivity",
    "Nut and Peanut Hypersensitivity",
    "Nutrition Disorders",
    "Nutritional and Metabolic Diseases",
    "Nystagmus, Congenital",
    "Nystagmus, Pathologic",
    "OEIS Complex",
    "Obesity Hypoventilation Syndrome",
    "Obstetric Labor Complications",
    "Obstetric Labor, Premature",
    "Occupational Diseases",
    "Ocular Hypertension",
    "Ocular Hypotension",
    "Ocular Motility Disorders",
    "Oculocerebrorenal Syndrome",
    "Oculomotor Nerve Diseases",
    "Odontogenic Cysts",
    "Oesophagostomiasis",
    "Olfaction Disorders",
    "Olfactory Nerve Diseases",
    "Oligohydramnios",
    "Oligospermia",
    "Olivary Degeneration",
    "Olivopontocerebellar Atrophies",
    "Onchocerciasis",
    "Onchocerciasis, Ocular",
    "Onycholysis",
    "Onychomycosis",
    "Oophoritis",
    "Ophthalmia Neonatorum",
    "Ophthalmia, Sympathetic",
    "Ophthalmoplegia, Chronic Progressive External",
    "Ophthalmoplegic Migraine",
    "Opioid-Induced Constipation",
    "Opisthorchiasis",
    "Opportunistic Infections",
    "Opsoclonus-Myoclonus Syndrome",
    "Optic Atrophy",
    "Optic Atrophy, Autosomal Dominant",
    "Optic Atrophy, Hereditary, Leber",
    "Optic Disk Drusen",
    "Optic Nerve Diseases",
    "Optic Nerve Hypoplasia",
    "Optic Neuritis",
    "Optic Neuropathy, Ischemic",
    "Oral Allergy Syndrome",
    "Oral Submucous Fibrosis",
    "Oral Ulcer",
    "Orbital Cellulitis",
    "Orbital Diseases",
    "Orbital Myositis",
    "Orbital Pseudotumor",
    "Orchitis",
    "Organizing Pneumonia",
    "Ornithine Carbamoyltransferase Deficiency Disease",
    "Orofaciodigital Syndromes",
    "Orthomyxoviridae Infections",
    "Osteitis",
    "Osteitis Deformans",
    "Osteitis Fibrosa Cystica",
    "Osteoarthritis",
    "Osteoarthritis, Hip",
    "Osteoarthritis, Knee",
    "Osteoarthritis, Spine",
    "Osteoarthropathy, Primary Hypertrophic",
    "Osteoarthropathy, Secondary Hypertrophic",
    "Osteochondritis",
    "Osteochondritis Dissecans",
    "Osteochondrodysplasias",
    "Osteochondrosis",
    "Osteogenesis Imperfecta",
    "Osteolysis, Essential",
    "Osteomalacia",
    "Osteomyelitis",
    "Osteopetrosis",
    "Osteophyte",
    "Osteopoikilosis",
    "Osteoporosis",
    "Osteoporosis, Postmenopausal",
    "Osteoradionecrosis",
    "Osteosclerosis",
    "Ostertagiasis",
    "Otitis",
    "Otitis Externa",
    "Otitis Media",
    "Otitis Media with Effusion",
    "Otitis Media, Suppurative",
    "Otomycosis",
    "Otorhinolaryngologic Diseases",
    "Otosclerosis",
    "Ovarian Cysts",
    "Ovarian Diseases",
    "Ovarian Hyperstimulation Syndrome",
    "Ovarian Torsion",
    "Overnutrition",
    "Overtraining Syndrome",
    "Ovotesticular Disorders of Sex Development",
    "Oxyuriasis",
    "Oxyurida Infections",
    "POEMS Syndrome",
    "Pachyonychia Congenita",
    "Pain Insensitivity, Congenital",
    "Pallister-Hall Syndrome",
    "Pancreatic Cyst",
    "Pancreatic Diseases",
    "Pancreatic Pseudocyst",
    "Pancreatitis",
    "Pancreatitis, Acute Hemorrhagic",
    "Pancreatitis, Acute Necrotizing",
    "Pancreatitis, Alcoholic",
    "Pancreatitis, Chronic",
    "Pancreatitis, Graft",
    "Pancytopenia",
    "Panniculitis",
    "Panniculitis, Lupus Erythematosus",
    "Panniculitis, Nodular Nonsuppurative",
    "Panniculitis, Peritoneal",
    "Panophthalmitis",
    "Pantothenate Kinase-Associated Neurodegeneration",
    "Panuveitis",
    "Papilledema",
    "Papillomavirus Infections",
    "Papillon-Lefevre Disease",
    "Paracoccidioidomycosis",
    "Paragonimiasis",
    "Parakeratosis",
    "Paralyses, Familial Periodic",
    "Paralysis",
    "Paralysis, Hyperkalemic Periodic",
    "Paralysis, Obstetric",
    "Parametritis",
    "Paramyxoviridae Infections",
    "Paranasal Sinus Diseases",
    "Paraneoplastic Cerebellar Degeneration",
    "Paraneoplastic Endocrine Syndromes",
    "Paraneoplastic Polyneuropathy",
    "Paraneoplastic Syndromes, Nervous System",
    "Paraneoplastic Syndromes, Ocular",
    "Paraparesis, Tropical Spastic",
    "Paraphimosis",
    "Parapsoriasis",
    "Parasitemia",
    "Parasitic Diseases",
    "Parasitic Diseases, Animal",
    "Parasomnias",
    "Parathyroid Diseases",
    "Paratuberculosis",
    "Paratyphoid Fever",
    "Parkinson Disease",
    "Parkinson Disease, Postencephalitic",
    "Parkinson Disease, Secondary",
    "Parkinsonian Disorders",
    "Paronychia",
    "Parotid Diseases",
    "Parotitis",
    "Paroxysmal Hemicrania",
    "Pars Planitis",
    "Parturient Paresis",
    "Parvoviridae Infections",
    "Pasteurella Infections",
    "Pasteurellaceae Infections",
    "Pasteurellosis, Pneumonic",
    "Patellofemoral Pain Syndrome",
    "Peanut Hypersensitivity",
    "Pediatric Obesity",
    "Pelger-Huet Anomaly",
    "Peliosis Hepatis",
    "Pelizaeus-Merzbacher Disease",
    "Pellagra",
    "Pelvic Floor Disorders",
    "Pelvic Girdle Pain",
    "Pelvic Infection",
    "Pelvic Inflammatory Disease",
    "Pelvic Organ Prolapse",
    "Pelvic Pain",
    "Pemphigoid Gestationis",
    "Pemphigoid, Benign Mucous Membrane",
    "Pemphigoid, Bullous",
    "Pemphigus",
    "Pemphigus, Benign Familial",
    "Penetrating Atherosclerotic Ulcer",
    "Penile Diseases",
    "Penile Induration",
    "Pentalogy of Cantrell",
    "Peptic Ulcer",
    "Peptic Ulcer Perforation",
    "Peri-Implantitis",
    "Periapical Abscess",
    "Periapical Diseases",
    "Periapical Granuloma",
    "Periapical Periodontitis",
    "Periarthritis",
    "Pericardial Effusion",
    "Pericarditis",
    "Pericarditis, Constrictive",
    "Pericarditis, Tuberculous",
    "Pericoronitis",
    "Perimeningeal Infections",
    "Perinephritis",
    "Periodontal Abscess",
    "Periodontal Atrophy",
    "Periodontal Attachment Loss",
    "Periodontal Cyst",
    "Periodontal Diseases",
    "Periodontitis",
    "Periostitis",
    "Peripartum Cardiomyopathy",
    "Peripheral Arterial Disease",
    "Peripheral Nervous System Diseases",
    "Peripheral Vascular Diseases",
    "Periprosthetic Fractures",
    "Peritoneal Diseases",
    "Peritonitis",
    "Peritonitis, Tuberculous",
    "Peritonsillar Abscess",
    "Periventricular Nodular Heterotopia",
    "Peroneal Neuropathies",
    "Peroxisomal Disorders",
    "Persian Gulf Syndrome",
    "Persistent Fetal Circulation Syndrome",
    "Persistent Hyperplastic Primary Vitreous",
    "Persistent Infection",
    "Persistent Vegetative State",
    "Peste-des-Petits-Ruminants",
    "Pestivirus Infections",
    "Petrositis",
    "Phaeohyphomycosis",
    "Phagocyte Bactericidal Dysfunction",
    "Pharyngeal Diseases",
    "Pharyngitis",
    "Phenylketonuria, Maternal",
    "Phenylketonurias",
    "Phimosis",
    "Phlebitis",
    "Phlebotomus Fever",
    "Phosphorus Metabolism Disorders",
    "Photosensitivity Disorders",
    "Phytoplasma Disease",
    "Pick Disease of the Brain",
    "Picornaviridae Infections",
    "Piebaldism",
    "Piedra",
    "Pierre Robin Syndrome",
    "Pigmentation Disorders",
    "Pinguecula",
    "Pinta",
    "Piscirickettsiaceae Infections",
    "Pituitary ACTH Hypersecretion",
    "Pituitary Apoplexy",
    "Pituitary Diseases",
    "Pityriasis",
    "Pityriasis Lichenoides",
    "Pityriasis Rosea",
    "Pityriasis Rubra Pilaris",
    "Placenta Accreta",
    "Placenta Diseases",
    "Placenta Previa",
    "Placenta, Retained",
    "Placental Insufficiency",
    "Plagiocephaly",
    "Plague",
    "Plant Diseases",
    "Plant Necrosis and Chlorosis",
    "Plasma Cell Granuloma, Pulmonary",
    "Platelet Storage Pool Deficiency",
    "Platypnea Orthodeoxia Syndrome",
    "Pleural Diseases",
    "Pleurisy",
    "Pleurodynia, Epidemic",
    "Pleuropneumonia",
    "Pleuropneumonia, Contagious",
    "Plummer-Vinson Syndrome",
    "Pneumatosis Cystoides Intestinalis",
    "Pneumocephalus",
    "Pneumococcal Infections",
    "Pneumoconiosis",
    "Pneumocystis Infections",
    "Pneumonia",
    "Pneumonia of Calves, Enzootic",
    "Pneumonia of Swine, Mycoplasmal",
    "Pneumonia, Aspiration",
    "Pneumonia, Atypical Interstitial, of Cattle",
    "Pneumonia, Bacterial",
    "Pneumonia, Lipid",
    "Pneumonia, Mycoplasma",
    "Pneumonia, Necrotizing",
    "Pneumonia, Pneumococcal",
    "Pneumonia, Pneumocystis",
    "Pneumonia, Progressive Interstitial, of Sheep",
    "Pneumonia, Rickettsial",
    "Pneumonia, Staphylococcal",
    "Pneumonia, Ventilator-Associated",
    "Pneumonia, Viral",
    "Pneumopericardium",
    "Pneumoperitoneum",
    "Pneumorrhachis",
    "Pneumothorax",
    "Pneumovirus Infections",
    "Poland Syndrome",
    "Poliomyelitis",
    "Poliomyelitis, Bulbar",
    "Polyarteritis Nodosa",
    "Polychondritis, Relapsing",
    "Polycystic Kidney Diseases",
    "Polycystic Kidney, Autosomal Dominant",
    "Polycystic Kidney, Autosomal Recessive",
    "Polycystic Ovary Syndrome",
    "Polycythemia",
    "Polyendocrinopathies, Autoimmune",
    "Polymicrogyria",
    "Polymorphic Catecholaminergic Ventricular Tachycardia",
    "Polymyalgia Rheumatica",
    "Polymyositis",
    "Polyneuropathies",
    "Polyomavirus Infections",
    "Polyradiculoneuropathy",
    "Polyradiculoneuropathy, Chronic Inflammatory Demyelinating",
    "Polyradiculopathy",
    "Popliteal Artery Aneurysm",
    "Popliteal Artery Entrapment Syndrome",
    "Popliteal Cyst",
    "Porcine Postweaning Multisystemic Wasting Syndrome",
    "Porcine Reproductive and Respiratory Syndrome",
    "Porencephaly",
    "Porokeratosis",
    "Porphyria Cutanea Tarda",
    "Porphyria, Acute Intermittent",
    "Porphyria, Erythropoietic",
    "Porphyria, Hepatoerythropoietic",
    "Porphyria, Variegate",
    "Porphyrias",
    "Porphyrias, Hepatic",
    "Positive-Pressure Respiration, Intrinsic",
    "Post-Acute COVID-19 Syndrome",
    "Post-Cardiac Arrest Syndrome",
    "Post-Concussion Syndrome",
    "Post-Infectious Disorders",
    "Post-Lyme Disease Syndrome",
    "Post-Traumatic Headache",
    "Postcholecystectomy Syndrome",
    "Posterior Cervical Sympathetic Syndrome",
    "Posterior Leukoencephalopathy Syndrome",
    "Posterior Tibial Tendon Dysfunction",
    "Postgastrectomy Syndromes",
    "Postpartum Thyroiditis",
    "Postpericardiotomy Syndrome",
    "Postphlebitic Syndrome",
    "Postpoliomyelitis Syndrome",
    "Postthrombotic Syndrome",
    "Postural Orthostatic Tachycardia Syndrome",
    "Potassium Deficiency",
    "Pott Puffy Tumor",
    "Pouchitis",
    "Poult Enteritis Mortality Syndrome",
    "Poultry Diseases",
    "Poxviridae Infections",
    "Prader-Willi Syndrome",
    "Pre-Eclampsia",
    "Pre-Excitation Syndromes",
    "Pre-Excitation, Mahaim-Type",
    "Prediabetic State",
    "Pregnancy Complications",
    "Pregnancy Complications, Cardiovascular",
    "Pregnancy Complications, Hematologic",
    "Pregnancy Complications, Infectious",
    "Pregnancy Complications, Parasitic",
    "Pregnancy in Diabetics",
    "Pregnancy, Abdominal",
    "Pregnancy, Angular",
    "Pregnancy, Cornual",
    "Pregnancy, Ectopic",
    "Pregnancy, Heterotopic",
    "Pregnancy, High-Risk",
    "Pregnancy, Interstitial",
    "Pregnancy, Ovarian",
    "Pregnancy, Prolonged",
    "Pregnancy, Tubal",
    "Premature Ejaculation",
    "Premenstrual Dysphoric Disorder",
    "Premenstrual Syndrome",
    "Presbyopia",
    "Pressure Ulcer",
    "Priapism",
    "Primary Dysautonomias",
    "Primary Immunodeficiency Diseases",
    "Primary Myelofibrosis",
    "Primary Ovarian Insufficiency",
    "Primate Diseases",
    "Prion Diseases",
    "Proctitis",
    "Proctocolitis",
    "Progeria",
    "Prolidase Deficiency",
    "Propionic Acidemia",
    "Propofol Infusion Syndrome",
    "Prostatic Diseases",
    "Prostatitis",
    "Protein C Deficiency",
    "Protein Deficiency",
    "Protein S Deficiency",
    "Protein-Energy Malnutrition",
    "Protein-Losing Enteropathies",
    "Proteinuria",
    "Proteus Infections",
    "Protoporphyria, Erythropoietic",
    "Protozoan Infections",
    "Protozoan Infections, Animal",
    "Prurigo",
    "Pruritus Vulvae",
    "Pseudarthrosis",
    "Pseudobulbar Palsy",
    "Pseudohypoaldosteronism",
    "Pseudohypoparathyroidism",
    "Pseudolymphoma",
    "Pseudomonas Infections",
    "Pseudopseudohypoparathyroidism",
    "Pseudorabies",
    "Pseudotumor Cerebri",
    "Pseudoxanthoma Elasticum",
    "Psittacosis",
    "Psoas Abscess",
    "Psoriasis",
    "Puberty, Delayed",
    "Puberty, Precocious",
    "Pudendal Neuralgia",
    "Puerperal Disorders",
    "Puerperal Infection",
    "Pulmonary Adenomatosis, Ovine",
    "Pulmonary Alveolar Proteinosis",
    "Pulmonary Arterial Hypertension",
    "Pulmonary Aspergillosis",
    "Pulmonary Atelectasis",
    "Pulmonary Disease, Chronic Obstructive",
    "Pulmonary Edema",
    "Pulmonary Embolism",
    "Pulmonary Emphysema",
    "Pulmonary Eosinophilia",
    "Pulmonary Fibrosis",
    "Pulmonary Heart Disease",
    "Pulmonary Infarction",
    "Pulmonary Subvalvular Stenosis",
    "Pulmonary Valve Insufficiency",
    "Pulmonary Valve Stenosis",
    "Pulmonary Veno-Occlusive Disease",
    "Pulpitis",
    "Pupil Disorders",
    "Pure Autonomic Failure",
    "Purine-Pyrimidine Metabolism, Inborn Errors",
    "Purpura",
    "Purpura Fulminans",
    "Purpura, Hyperglobulinemic",
    "Purpura, Thrombocytopenic",
    "Purpura, Thrombocytopenic, Idiopathic",
    "Purpura, Thrombotic Thrombocytopenic",
    "Pycnodysostosis",
    "Pyelitis",
    "Pyelocystitis",
    "Pyelonephritis",
    "Pyelonephritis, Xanthogranulomatous",
    "Pyloric Stenosis",
    "Pyloric Stenosis, Hypertrophic",
    "Pyoderma",
    "Pyoderma Gangrenosum",
    "Pyometra",
    "Pyonephrosis",
    "Pyruvate Carboxylase Deficiency Disease",
    "Pyruvate Dehydrogenase Complex Deficiency Disease",
    "Pyruvate Metabolism, Inborn Errors",
    "Pythiosis",
    "Pyuria",
    "Q Fever",
    "Quadriplegia",
    "REM Sleep Behavior Disorder",
    "REM Sleep Parasomnias",
    "RNA Virus Infections",
    "Rabies",
    "Radial Neuropathy",
    "Radiation Fibrosis Syndrome",
    "Radiation Pneumonitis",
    "Radicular Cyst",
    "Radiculopathy",
    "Radiodermatitis",
    "Ranula",
    "Rare Diseases",
    "Rat-Bite Fever",
    "Raynaud Disease",
    "Rectal Diseases",
    "Rectal Prolapse",
    "Rectocele",
    "Red-Cell Aplasia, Pure",
    "Refeeding Syndrome",
    "Reflex Sympathetic Dystrophy",
    "Refractive Errors",
    "Refsum Disease",
    "Refsum Disease, Infantile",
    "Relapsing Fever",
    "Relative Energy Deficiency in Sport",
    "Renal Aminoacidurias",
    "Renal Artery Obstruction",
    "Renal Insufficiency",
    "Renal Insufficiency, Chronic",
    "Renal Nutcracker Syndrome",
    "Renal Tubular Transport, Inborn Errors",
    "Reoviridae Infections",
    "Reproductive Tract Infections",
    "Respiration Disorders",
    "Respiratory Aspiration of Gastric Contents",
    "Respiratory Distress Syndrome",
    "Respiratory Distress Syndrome, Newborn",
    "Respiratory Syncytial Virus Infections",
    "Respiratory System Abnormalities",
    "Respiratory Tract Diseases",
    "Respiratory Tract Infections",
    "Respirovirus Infections",
    "Restless Legs Syndrome",
    "Reticuloendotheliosis, Avian",
    "Retinal Artery Occlusion",
    "Retinal Degeneration",
    "Retinal Detachment",
    "Retinal Diseases",
    "Retinal Drusen",
    "Retinal Dysplasia",
    "Retinal Dystrophies",
    "Retinal Necrosis Syndrome, Acute",
    "Retinal Perforations",
    "Retinal Vasculitis",
    "Retinal Vein Occlusion",
    "Retinitis",
    "Retinitis Pigmentosa",
    "Retinopathy of Prematurity",
    "Retinoschisis",
    "Retrocochlear Diseases",
    "Retrograde Ejaculation",
    "Retropharyngeal Abscess",
    "Retroviridae Infections",
    "Rett Syndrome",
    "Reye Syndrome",
    "Rh Isoimmunization",
    "Rhabditida Infections",
    "Rhabdoviridae Infections",
    "Rheumatic Diseases",
    "Rheumatic Fever",
    "Rheumatic Heart Disease",
    "Rheumatoid Vasculitis",
    "Rhinitis",
    "Rhinitis, Allergic",
    "Rhinitis, Allergic, Perennial",
    "Rhinitis, Allergic, Seasonal",
    "Rhinitis, Atrophic",
    "Rhinitis, Vasomotor",
    "Rhinophyma",
    "Rhinoscleroma",
    "Rhinosinusitis",
    "Rhinosporidiosis",
    "Riboflavin Deficiency",
    "Rickets",
    "Rickets, Hypophosphatemic",
    "Rickettsia Infections",
    "Rickettsiaceae Infections",
    "Rift Valley Fever",
    "Rinderpest",
    "Rocky Mountain Spotted Fever",
    "Rodent Diseases",
    "Romano-Ward Syndrome",
    "Root Caries",
    "Root Resorption",
    "Rosacea",
    "Roseolovirus Infections",
    "Ross River Virus Infection",
    "Rotator Cuff Tear Arthropathy",
    "Rotavirus Infections",
    "Rothmund-Thomson Syndrome",
    "Rubella",
    "Rubella Syndrome, Congenital",
    "Rubivirus Infections",
    "Rubulavirus Infections",
    "Rumination Syndrome",
    "ST Elevation Myocardial Infarction",
    "Sacroiliitis",
    "Sagittal Sinus Thrombosis",
    "Salivary Gland Diseases",
    "Salmonella Food Poisoning",
    "Salmonella Infections",
    "Salmonella Infections, Animal",
    "Salpingitis",
    "Sandhoff Disease",
    "Sarcocystosis",
    "Sarcoglycanopathies",
    "Sarcoidosis",
    "Sarcoidosis, Pulmonary",
    "Scabies",
    "Scalp Dermatoses",
    "Scarlet Fever",
    "Scheuermann Disease",
    "Schistosomiasis",
    "Schistosomiasis haematobia",
    "Schistosomiasis japonica",
    "Schistosomiasis mansoni",
    "Schizencephaly",
    "Schnitzler Syndrome",
    "Sciatic Neuropathy",
    "Scleral Diseases",
    "Scleredema Adultorum",
    "Scleritis",
    "Scleroderma, Diffuse",
    "Scleroderma, Limited",
    "Scleroderma, Localized",
    "Scleroderma, Systemic",
    "Scleromyxedema",
    "Scrapie",
    "Screw Worm Infection",
    "Scrub Typhus",
    "Scurvy",
    "Sea-Blue Histiocyte Syndrome",
    "Sebaceous Gland Diseases",
    "Secernentea Infections",
    "Semicircular Canal Dehiscence",
    "Sensation Disorders",
    "Sepsis",
    "Sepsis-Associated Encephalopathy",
    "Septo-Optic Dysplasia",
    "Serratia Infections",
    "Sertoli Cell-Only Syndrome",
    "Serum Sickness",
    "Setariasis",
    "Severe Acute Malnutrition",
    "Severe Acute Respiratory Syndrome",
    "Severe Combined Immunodeficiency",
    "Severe Dengue",
    "Severe Fever with Thrombocytopenia Syndrome",
    "Sex Chromosome Aberrations",
    "Sex Chromosome Disorders",
    "Sexual Dysfunction, Physiological",
    "Sexual Infantilism",
    "Sexually Transmitted Diseases",
    "Sexually Transmitted Diseases, Bacterial",
    "Sexually Transmitted Diseases, Viral",
    "Sheep Diseases",
    "Shellfish Hypersensitivity",
    "Shock, Septic",
    "Short Bowel Syndrome",
    "Short Rib-Polydactyly Syndrome",
    "Shoulder Dystocia",
    "Shoulder Impingement Syndrome",
    "Shwachman-Diamond Syndrome",
    "Shwartzman Phenomenon",
    "Shy-Drager Syndrome",
    "Sialadenitis",
    "Sialic Acid Storage Disease",
    "Sialometaplasia, Necrotizing",
    "Sialorrhea",
    "Sick Building Syndrome",
    "Sick Sinus Syndrome",
    "Sickle Cell Trait",
    "Siderosis",
    "Sigmoid Diseases",
    "Silicosis",
    "Silicotuberculosis",
    "Silo Filler's Disease",
    "Silver-Russell Syndrome",
    "Simian Acquired Immunodeficiency Syndrome",
    "Sinistral Portal Hypertension",
    "Sinoatrial Block",
    "Sinus Thrombosis, Intracranial",
    "Sinusitis",
    "Sjogren's Syndrome",
    "Sjogren-Larsson Syndrome",
    "Skin Abnormalities",
    "Skin Diseases",
    "Skin Diseases, Bacterial",
    "Skin Diseases, Eczematous",
    "Skin Diseases, Genetic",
    "Skin Diseases, Infectious",
    "Skin Diseases, Metabolic",
    "Skin Diseases, Papulosquamous",
    "Skin Diseases, Parasitic",
    "Skin Diseases, Vascular",
    "Skin Diseases, Vesiculobullous",
    "Skin Diseases, Viral",
    "Skin Ulcer",
    "Skin and Connective Tissue Diseases",
    "Skull Fractures",
    "Sleep Apnea Syndromes",
    "Sleep Apnea, Central",
    "Sleep Apnea, Obstructive",
    "Sleep Arousal Disorders",
    "Sleep Bruxism",
    "Sleep Disorders, Intrinsic",
    "Sleep Initiation and Maintenance Disorders",
    "Slipped Capital Femoral Epiphyses",
    "Slow Virus Diseases",
    "Small Fiber Neuropathy",
    "Smallpox",
    "Smith-Lemli-Opitz Syndrome",
    "Smith-Magenis Syndrome",
    "Sneddon Syndrome",
    "Soft Tissue Infections",
    "Soft Tissue Injuries",
    "Somatosensory Disorders",
    "Somnambulism",
    "Sotos Syndrome",
    "Sparganosis",
    "Spasms, Infantile",
    "Spastic Paraplegia, Hereditary",
    "Specific Language Disorder",
    "Speech Disorders",
    "Spermatic Cord Torsion",
    "Spermatocele",
    "Sphenoid Sinusitis",
    "Spherocytosis, Hereditary",
    "Sphincter of Oddi Dysfunction",
    "Sphingolipidoses",
    "Spinal Cord Compression",
    "Spinal Cord Diseases",
    "Spinal Cord Ischemia",
    "Spinal Cord Vascular Diseases",
    "Spinal Curvatures",
    "Spinal Diseases",
    "Spinal Muscular Atrophies of Childhood",
    "Spinal Osteochondrosis",
    "Spinal Osteophytosis",
    "Spinal Stenosis",
    "Spinocerebellar Ataxias",
    "Spinocerebellar Degenerations",
    "Spirochaetales Infections",
    "Spirurida Infections",
    "Splenic Diseases",
    "Splenic Infarction",
    "Splenosis",
    "Spondylarthritis",
    "Spondylarthropathies",
    "Spondylitis",
    "Spondylitis, Ankylosing",
    "Spondylolisthesis",
    "Spondylolysis",
    "Spondylosis",
    "Sporotrichosis",
    "Spotted Fever Group Rickettsiosis",
    "Sprue, Tropical",
    "Staphylococcal Food Poisoning",
    "Staphylococcal Infections",
    "Staphylococcal Scalded Skin Syndrome",
    "Staphylococcal Skin Infections",
    "Stargardt Disease",
    "Status Asthmaticus",
    "Status Epilepticus",
    "Steatitis",
    "Steatocystoma Multiplex",
    "Steatorrhea",
    "Stenosis, Pulmonary Artery",
    "Stenosis, Pulmonary Vein",
    "Steroid Metabolism, Inborn Errors",
    "Stevens-Johnson Syndrome",
    "Stiff-Person Syndrome",
    "Still's Disease, Adult-Onset",
    "Stomach Diseases",
    "Stomach Rupture",
    "Stomach Ulcer",
    "Stomach Volvulus",
    "Stomatitis",
    "Stomatitis, Aphthous",
    "Stomatitis, Denture",
    "Stomatitis, Herpetic",
    "Stomatognathic Diseases",
    "Stomatognathic System Abnormalities",
    "Strabismus",
    "Streptococcal Infections",
    "Striatonigral Degeneration",
    "Stroke",
    "Stroke, Lacunar",
    "Strongyle Infections, Equine",
    "Strongylida Infections",
    "Strongyloidiasis",
    "Stupor",
    "Sturge-Weber Syndrome",
    "Subacute Sclerosing Panencephalitis",
    "Subarachnoid Hemorrhage",
    "Subclavian Steal Syndrome",
    "Submandibular Gland Diseases",
    "Subphrenic Abscess",
    "Sulfatidosis",
    "Sulfhemoglobinemia",
    "Superior Mesenteric Artery Syndrome",
    "Superior Vena Cava Syndrome",
    "Supraglottitis",
    "Supranuclear Palsy, Progressive",
    "Susac Syndrome",
    "Swayback",
    "Sweat Gland Diseases",
    "Sweating, Gustatory",
    "Sweet Syndrome",
    "Swine Diseases",
    "Swine Erysipelas",
    "Swine Vesicular Disease",
    "Syncope, Vasovagal",
    "Syndrome",
    "Synovitis",
    "Synucleinopathies",
    "Syphilis",
    "Syphilis, Cardiovascular",
    "Syphilis, Congenital",
    "Syphilis, Cutaneous",
    "Syphilis, Latent",
    "Syringomyelia",
    "Systemic Inflammatory Response Syndrome",
    "Systemic Vasculitis",
    "T-Lymphocytopenia, Idiopathic CD4-Positive",
    "TDP-43 Proteinopathies",
    "Tabes Dorsalis",
    "Tachycardia, Atrioventricular Nodal Reentry",
    "Tachycardia, Ectopic Atrial",
    "Tachycardia, Ectopic Junctional",
    "Tachycardia, Paroxysmal",
    "Tachycardia, Reciprocating",
    "Tachycardia, Sinoatrial Nodal Reentry",
    "Tachycardia, Sinus",
    "Tachycardia, Supraventricular",
    "Taeniasis",
    "Takayasu Arteritis",
    "Tangier Disease",
    "Tardive Dyskinesia",
    "Tarsal Tunnel Syndrome",
    "Taste Disorders",
    "Tauopathies",
    "Tay-Sachs Disease",
    "Tay-Sachs Disease, AB Variant",
    "Telangiectasia, Hereditary Hemorrhagic",
    "Telangiectasis",
    "Temporomandibular Joint Disorders",
    "Temporomandibular Joint Dysfunction Syndrome",
    "Tendinopathy",
    "Tendon Entrapment",
    "Tennis Elbow",
    "Tenosynovitis",
    "Tension-Type Headache",
    "Teratozoospermia",
    "Testicular Diseases",
    "Testicular Hydrocele",
    "Tetanus",
    "Tetany",
    "Thalamic Diseases",
    "Thalassemia",
    "Theileriasis",
    "Thiamine Deficiency",
    "Thoracic Diseases",
    "Thoracic Outlet Syndrome",
    "Thrombasthenia",
    "Thromboangiitis Obliterans",
    "Thrombocythemia, Essential",
    "Thrombocytopenia",
    "Thrombocytopenia, Neonatal Alloimmune",
    "Thrombocytosis",
    "Thromboinflammation",
    "Thrombophilia",
    "Thrombophlebitis",
    "Thrombotic Microangiopathies",
    "Thrombotic Stroke",
    "Thymus Hyperplasia",
    "Thyroglossal Cyst",
    "Thyroid Crisis",
    "Thyroid Diseases",
    "Thyroid Dysgenesis",
    "Thyroid Hormone Resistance Syndrome",
    "Thyroiditis",
    "Thyroiditis, Autoimmune",
    "Thyroiditis, Subacute",
    "Thyroiditis, Suppurative",
    "Thyrotoxicosis",
    "Tibial Neuropathy",
    "Tic Disorders",
    "Tick Infestations",
    "Tick Paralysis",
    "Tick Toxicoses",
    "Tick-Borne Diseases",
    "Tietze's Syndrome",
    "Tinea",
    "Tinea Capitis",
    "Tinea Cruris",
    "Tinea Favosa",
    "Tinea Pedis",
    "Tinea Versicolor",
    "Tissue Adhesions",
    "Togaviridae Infections",
    "Tolosa-Hunt Syndrome",
    "Tongue Diseases",
    "Tongue, Fissured",
    "Tongue, Hairy",
    "Tonsillitis",
    "Tooth Ankylosis",
    "Tooth Attrition",
    "Tooth Demineralization",
    "Tooth Diseases",
    "Tooth Erosion",
    "Tooth Eruption, Ectopic",
    "Tooth Loss",
    "Tooth Resorption",
    "Tooth Wear",
    "Tooth, Nonvital",
    "Torovirus Infections",
    "Torsades de Pointes",
    "Toxascariasis",
    "Toxemia",
    "Toxocariasis",
    "Toxoplasmosis",
    "Toxoplasmosis, Animal",
    "Toxoplasmosis, Cerebral",
    "Toxoplasmosis, Congenital",
    "Toxoplasmosis, Ocular",
    "Tracheal Diseases",
    "Tracheal Stenosis",
    "Tracheitis",
    "Tracheobronchomalacia",
    "Tracheomalacia",
    "Trachoma",
    "Travel-Related Illness",
    "Trematode Infections",
    "Trench Fever",
    "Treponemal Infections",
    "Trichiasis",
    "Trichinellosis",
    "Trichomonas Infections",
    "Trichomonas Vaginitis",
    "Trichosporonosis",
    "Trichostrongyloidiasis",
    "Trichostrongylosis",
    "Trichothiodystrophy Syndromes",
    "Trichuriasis",
    "Tricuspid Valve Insufficiency",
    "Tricuspid Valve Prolapse",
    "Tricuspid Valve Stenosis",
    "Trigeminal Autonomic Cephalalgias",
    "Trigeminal Nerve Diseases",
    "Trigeminal Neuralgia",
    "Trigger Finger Disorder",
    "Trismus",
    "Trisomy 18 Syndrome",
    "Trochlear Nerve Diseases",
    "Trombiculiasis",
    "Trypanosomiasis",
    "Trypanosomiasis, African",
    "Trypanosomiasis, Bovine",
    "Tuberculoma",
    "Tuberculoma, Intracranial",
    "Tuberculosis",
    "Tuberculosis, Avian",
    "Tuberculosis, Bovine",
    "Tuberculosis, Cardiovascular",
    "Tuberculosis, Central Nervous System",
    "Tuberculosis, Cutaneous",
    "Tuberculosis, Endocrine",
    "Tuberculosis, Extrapulmonary",
    "Tuberculosis, Female Genital",
    "Tuberculosis, Gastrointestinal",
    "Tuberculosis, Hepatic",
    "Tuberculosis, Laryngeal",
    "Tuberculosis, Lymph Node",
    "Tuberculosis, Male Genital",
    "Tuberculosis, Meningeal",
    "Tuberculosis, Miliary",
    "Tuberculosis, Multidrug-Resistant",
    "Tuberculosis, Ocular",
    "Tuberculosis, Oral",
    "Tuberculosis, Osteoarticular",
    "Tuberculosis, Pleural",
    "Tuberculosis, Pulmonary",
    "Tuberculosis, Renal",
    "Tuberculosis, Spinal",
    "Tuberculosis, Splenic",
    "Tuberculosis, Urogenital",
    "Tularemia",
    "Tumor Lysis Syndrome",
    "Tungiasis",
    "Turner Syndrome",
    "Tympanic Membrane Perforation",
    "Tympanosclerosis",
    "Typhlitis",
    "Typhoid Fever",
    "Typhus, Endemic Flea-Borne",
    "Typhus, Epidemic Louse-Borne",
    "Tyrosinemias",
    "Ulnar Nerve Compression Syndromes",
    "Ulnar Neuropathies",
    "Undiagnosed Diseases",
    "Undifferentiated Connective Tissue Diseases",
    "Unverricht-Lundborg Syndrome",
    "Upper Extremity Deep Vein Thrombosis",
    "Urachal Cyst",
    "Urea Cycle Disorders, Inborn",
    "Ureaplasma Infections",
    "Uremia",
    "Ureteral Diseases",
    "Ureteral Obstruction",
    "Ureterocele",
    "Ureterolithiasis",
    "Urethral Diseases",
    "Urethral Obstruction",
    "Urethral Stricture",
    "Urethritis",
    "Urinary Bladder Diseases",
    "Urinary Bladder Neck Obstruction",
    "Urinary Bladder, Neurogenic",
    "Urinary Incontinence",
    "Urinary Incontinence, Stress",
    "Urinary Incontinence, Urge",
    "Urinary Tract Infections",
    "Urination Disorders",
    "Urogenital Abnormalities",
    "Urogenital Diseases",
    "Urolithiasis",
    "Urologic Diseases",
    "Urticaria",
    "Urticaria Pigmentosa",
    "Urticaria, Solar",
    "Usher Syndromes",
    "Uterine Cervical Diseases",
    "Uterine Cervical Erosion",
    "Uterine Cervical Incompetence",
    "Uterine Cervicitis",
    "Uterine Diseases",
    "Uterine Inversion",
    "Uterine Perforation",
    "Uterine Prolapse",
    "Uterine Rupture",
    "Uveal Diseases",
    "Uveal Effusion Syndrome",
    "Uveal Melanoma",
    "Uveitis",
    "Uveitis, Anterior",
    "Uveitis, Intermediate",
    "Uveitis, Posterior",
    "Uveitis, Suppurative",
    "Uveomeningoencephalitic Syndrome",
    "Uveoparotid Fever",
    "Vaccine-Preventable Diseases",
    "Vaccinia",
    "Vaginal Discharge",
    "Vaginal Diseases",
    "Vaginismus",
    "Vaginitis",
    "Vaginosis, Bacterial",
    "Vagus Nerve Diseases",
    "Varicella Zoster Virus Infection",
    "Varicocele",
    "Varicose Ulcer",
    "Vasa Previa",
    "Vascular Depression",
    "Vascular Diseases",
    "Vascular Headaches",
    "Vasculitis",
    "Vasculitis, Central Nervous System",
    "Vasculitis, Leukocytoclastic, Cutaneous",
    "Vaso-Occlusive Crises",
    "Vasospasm, Intracranial",
    "Vector Borne Diseases",
    "Venom Hypersensitivity",
    "Venous Insufficiency",
    "Ventilator-Induced Lung Injury",
    "Ventricular Outflow Obstruction",
    "Ventricular Outflow Obstruction, Left",
    "Ventricular Outflow Obstruction, Right",
    "Ventricular Septal Rupture",
    "Vertebral Artery Dissection",
    "Vertebrobasilar Insufficiency",
    "Vesico-Ureteral Reflux",
    "Vesicular Exanthema of Swine",
    "Vesicular Stomatitis",
    "Vestibular Diseases",
    "Vestibular Neuronitis",
    "Vestibulocochlear Nerve Diseases",
    "Vibrio Infections",
    "Viral Zoonoses",
    "Viremia",
    "Virus Diseases",
    "Visceral Prolapse",
    "Vision Disorders",
    "Vision, Low",
    "Visna",
    "Vitamin A Deficiency",
    "Vitamin B 12 Deficiency",
    "Vitamin B 6 Deficiency",
    "Vitamin B Deficiency",
    "Vitamin D Deficiency",
    "Vitamin E Deficiency",
    "Vitamin K Deficiency",
    "Vitamin K Deficiency Bleeding",
    "Vitelliform Macular Dystrophy",
    "Vitiligo",
    "Vitreoretinopathy, Proliferative",
    "Vitreous Detachment",
    "Vocal Cord Dysfunction",
    "Vocal Cord Paralysis",
    "Voice Disorders",
    "Vulvar Diseases",
    "Vulvar Lichen Sclerosus",
    "Vulvar Vestibulitis",
    "Vulvitis",
    "Vulvodynia",
    "Vulvovaginitis",
    "Waardenburg Syndrome",
    "Walker-Warburg Syndrome",
    "Wandering Spleen",
    "Warts",
    "Wasting Disease, Chronic",
    "Wasting Syndrome",
    "Water Intoxication",
    "Waterborne Diseases",
    "Waterhouse-Friderichsen Syndrome",
    "Weil Disease",
    "Weill-Marchesani Syndrome",
    "Werner Syndrome",
    "Wernicke Encephalopathy",
    "West Nile Fever",
    "Wet Macular Degeneration",
    "Wheat Hypersensitivity",
    "Whipple Disease",
    "White Dot Syndromes",
    "White Heifer Disease",
    "White Muscle Disease",
    "Whooping Cough",
    "Williams Syndrome",
    "Wiskott-Aldrich Syndrome",
    "Wissler's Syndrome",
    "Wolf-Hirschhorn Syndrome",
    "Wolff-Parkinson-White Syndrome",
    "Wolfram Syndrome",
    "Wolman Disease",
    "X-Linked Combined Immunodeficiency Diseases",
    "X-Linked Emery-Dreifuss Muscular Dystrophy",
    "XYY Karyotype",
    "Xanthogranuloma, Juvenile",
    "Xanthomatosis",
    "Xanthomatosis, Cerebrotendinous",
    "Xerophthalmia",
    "Xerostomia",
    "Yaws",
    "Yellow Fever",
    "Yellow Nail Syndrome",
    "Yersinia Infections",
    "Yersinia pseudotuberculosis Infections",
    "Zellweger Syndrome",
    "Zenker Diverticulum",
    "Zika Virus Infection",
    "Zollinger-Ellison Syndrome",
    "Zoonoses",
    "Zoster Sine Herpete",
    "Zygomycosis",
    "alpha 1-Antitrypsin Deficiency",
    "alpha-Mannosidosis",
    "alpha-Thalassemia",
    "beta-Mannosidosis",
    "beta-Thalassemia",
    "delta-Thalassemia",
    "von Hippel-Lindau Disease",
    "von Willebrand Disease, Type 1",
    "von Willebrand Disease, Type 2",
    "von Willebrand Disease, Type 3",
    "von Willebrand Diseases"
])
